DARMA-tasking/vt

- src/vt/termination/interval/discrete_interval.h
- src/vt/termination/interval/integral_set.h
- src/vt/termination/interval/interval.h
- src/vt/termination/term_window.cc
- src/vt/termination/term_window.h
- src/vt/termination/termination.cc
- tests/unit/termination/test_integral_set.cc
- Implemented new integral set vt::IntegralSet, that makes epoch alloc/dealloc far more efficient
- Uses a sorted, non-overlapping interval tree to implement automatic compaction
- Holes in the release set of epochs no longer inhibit wrap around (a major problem for tree-structured epochs)
> 410 Integral Set 

- src/vt/registry/auto/auto_registry.cc
Return in order to avoid warning in release mode.  Addresses #428
> registry: remove compile warning with tracing

- src/vt/collective/reduce/operators/default_msg.h
- src/vt/collective/reduce/operators/functors/plus_op.h
- tests/unit/collectives/test_collectives_reduce.cc
ReduceVectorMsg is now serializable. 
A test has been added for vector of bool and vector of int.
The specialization `struct PlusOp< std::vector<bool> >` has been added because the general operation `v1[ii] += v2[ii];` doesn't work for std::vector of bool when `v1[ii] = v1[ii] + v2[ii];` works.
I think we can also change the operation from `v1[ii] += v2[ii];` to `v1[ii] = v1[ii] + v2[ii];` in the general PlusOp template but it's probably less optimized.
> 480 serialization reduce vec msg

- src/vt/vrt/collection/balance/baselb/baselb.cc
- src/vt/vrt/collection/balance/hierarchicallb/hierlb.cc
- src/vt/vrt/collection/balance/hierarchicallb/hierlb.h
- src/vt/vrt/collection/balance/hierarchicallb/hierlb_msgs.h
Fixes a race condition in HierarchicalLB, occurring in EMPIRE runs on kahuna. For now, add barriers to synchronize the setup of the tree with the following use of it. In the future, this could become an asynchronous reduction.
> 507 LB add barriers to synchronize the hierlb tree setup

- src/vt/messaging/active.cc
- src/vt/messaging/active.h
- src/vt/messaging/irecv_holder.h
#472 changes MPI_Recv to MPI_Irecv to mitigate excessively slow MPI_Recv under EMPIRE that appears to be waiting for the sender to finish unrelated work.
@lifflander @PhilMiller
> 472 Convert MPI_Recv to async MPI_Irecv

- tests/unit/collection/test_broadcast.cc
- tests/unit/collection/test_construct.cc
- tests/unit/collection/test_construct_idx_fst.cc
- tests/unit/collection/test_construct_idx_snd.cc
- tests/unit/collection/test_construct_no_idx.cc
- tests/unit/collection/test_index_types.cc
- tests/unit/collection/test_send.cc
- tests/unit/location/test_location.cc
- tests/unit/memory/test_memory_active.cc
This addresses all these warnings that have hung around for a long time:
```bash
/home/travis/build/DARMA-tasking/vt/tests/unit/memory/test_memory_active.cc:163:74: 
warning: ISO C++11 requires at least one argument for the "..." in a variadic macro INSTANTIATE_TYPED_TEST_CASE_P(test_mem_short,  TestMemoryActive, MsgShort);
```
> 512 Fix clang warning in tests due to gtest macro

- tests/unit/active/test_active_bcast_put.cc
- tests/unit/active/test_active_send.cc
- tests/unit/active/test_active_send_put.cc
This was causing an occasional test failure on Mutrino with Intel compilers.
> 515 Fix memory use-after-free bug in unit test

- tests/unit/collection/test_broadcast.cc
- tests/unit/collection/test_construct.cc
- tests/unit/collection/test_construct_idx_fst.cc
- tests/unit/collection/test_construct_idx_snd.cc
- tests/unit/collection/test_construct_no_idx.cc
- tests/unit/collection/test_index_types.cc
- tests/unit/collection/test_send.cc
- tests/unit/location/test_location.cc
- tests/unit/memory/test_memory_active.cc
Issue #517. Removed the trailing comma in the argument list for `INSTANTIATE_TYPED_TEST_CASE_P`, which only takes 3 arguments.
> 517 remove extraneous commas

- cmake/test_vt.cmake
- tests/CMakeLists.txt
Issue #519.  On Mutrino at least, ctest doesn't notice segfaults unless I have it grep for "Segmentation fault", potentially because of using srun to launch the tests.  With this improvement to the testing setup, I see that many unit tests and examples are segfaulting on Mutrino (whereas previously the segfaults were there but not brought to the user's attention). Note that I built with tracing and haven't checked to see how many of the segfaults are tracing-related.
> 519 fail on segfault

- src/vt/runtime/runtime.cc
Small fix to stop creating trace directory when tracing is not runtime enabled.
> 511 only create trace directory when runtime tracing is enabled

- src/vt/vrt/collection/balance/baselb/baselb.cc
The global migration count after LB runs is currently incorrect---this fixes the double counting on the number of migrations.
> 529 LB fix double-counted migration count

- src/vt/configs/arguments/args.cc
- src/vt/configs/arguments/args.h
- src/vt/configs/debug/debug_colorize.h
- src/vt/configs/debug/debug_print.h
- src/vt/runtime/runtime.cc
- Rules for configuration are defined (AND followed..);
logic happens immediately after parsing which ensures
only one isatty check (ioctl) and centralized logic handling.
Updated the setting/diagnostic messages to also align
with the rules.
Rules:
- no-color DISABLES color
- color ENABLES color
- auto-color (assumed default) enables color in terminal
(This makes VT consistent with tools like 'ls', or more so..)
- Removes unistd.h bleed - should be removed from other headers
- Consistently use defined colors and other minor formatting;
swith to 'standard' functions.
> 539 perf. colorization code and unify color selection

- src/vt/utils/demangle/demangle.cc
- src/vt/utils/demangle/demangle.h
- src/vt/utils/demangle/demangled_name.h
- Remove <regex> dependency; since this is gone from
the header as well, saves many hundreds of ms per
affected TU.. like, literally, 200ms+ per TU :|
- Moved non-effective inline functions to cc.
- Removed assorted aliases and converted to more idiomatic C++.
> 540 perf. cleanup for demangler.cc

- src/vt/configs/arguments/args.h
- src/vt/configs/debug/debug_colorize.h
- src/vt/configs/debug/debug_print.h
- src/vt/configs/error/common.h
- src/vt/configs/error/error.h
- src/vt/configs/error/error.impl.h
- src/vt/configs/error/hard_error.h
- src/vt/configs/error/pretty_print_message.cc
- src/vt/configs/error/pretty_print_message.h
- src/vt/configs/types/types_size.h
- src/vt/configs/types/types_type.h
- src/vt/event/event_id.cc
- src/vt/pipe/id/pipe_id.h
- src/vt/sequence/seq_closure.cc
- src/vt/termination/term_scope.cc
- src/vt/trace/trace_event.cc
- src/vt/utils/bits/bits_common.h
- src/vt/utils/bits/bits_counter.h
- src/vt/utils/bits/bits_packer.h
- src/vt/vrt/collection/balance/proc_stats.h
- src/vt/vrt/collection/proxy_builder/elm_proxy_builder.cc
- src/vt/vrt/collection/proxy_builder/elm_proxy_builder.h
- src/vt/vrt/proxy/proxy_bits.h
- src/vt/worker/worker_seq.cc
- Code does not have benefit being in header so..
moved to compile-once-CC-file.
And then FIXED a number of headers/code that broke
due to having the transitive dependency spider web
removed.
- Removed last gobal usage of unistd.h and cstdio
from headers - should add wiki note about the 'allowed headers'
that may be included in .h files.. so much global pollution.
- As added bonus, uses cached std::string hostname.
- Fix broken header includes exposed when headers stopped
being included from 'pretty_print_message.h'
Now 'types_headers.h' should be resolveable at the TOP of the header graph;
updated bits_counter to accomodate.
> 541 move 'pretty print message' to cc

- src/vt/topos/location/location.impl.h
Access the static variable directly as opposed to using the pointer.
> 527 Fix access to null pointer. Add minor clean-ups.

- src/vt/configs/arguments/args.cc
- src/vt/configs/arguments/args.h
- src/vt/messaging/active.cc
- src/vt/messaging/active.h
- src/vt/messaging/irecv_holder.h
- src/vt/runtime/runtime.cc
- src/vt/trace/trace.cc
Issue #552.  I have created this PR for merging into 1.0.0 because that's where I branched off.  I don't think it's appropriate to merge directly into 1.0.0, so I have marked this as WIP.  However, this is complete and **ready for review** as far as I am concerned.
This adds tracing of MPI_Isend, MPI_Irecv, and the completion of MPI_Irecv when the new --vt_trace_mpi option is used.  I implemented it differently than @lifflander did in the past due to the conditional (so couldn't use scoping) and the desire to include the message size as a note associated with the MPI_Irecv event itself rather than as a precursor note.
> 552 add tracing of mpi calls

- src/vt/configs/debug/debug_var_unused.h
- What's faster than instantiating a tuple?
Not instantiating a tuple.
Tuple instantiation is SLLLLLOW in comparison,
especially over many more types.
Compilers may (or may not) optimize out entire construct.
Fixes #583
> 538 remove tuple from debug::useVars

- src/vt/group/collective/group_info_collective.cc
Fix race condition (exposed by priorities), breaking on `doppio` during group creation (occurs each time a new collection is created).
Fixes #570
> #570 group fix race condition in collective group creation

- src/CMakeLists.txt
- src/vt/configs/arguments/args.cc
- src/vt/configs/arguments/args.h
- src/vt/messaging/active.cc
- src/vt/messaging/dependent_send_chain.h
- src/vt/runtime/runtime.cc
- src/vt/scheduler/prioritized_work_unit.h
- src/vt/scheduler/scheduler.cc
- src/vt/scheduler/scheduler.h
- src/vt/scheduler/scheduler.impl.h
- src/vt/scheduler/work_unit.h
- src/vt/termination/dijkstra-scholten/ds.cc
- src/vt/termination/dijkstra-scholten/ds.h
- src/vt/termination/epoch_dependency.cc
- src/vt/termination/epoch_dependency.h
- src/vt/termination/graph/epoch_graph.cc
- src/vt/termination/graph/epoch_graph.h
- src/vt/termination/graph/epoch_graph_reduce.h
- src/vt/termination/term_msgs.h
- src/vt/termination/term_state.cc
- src/vt/termination/term_state.h
- src/vt/termination/termination.cc
- src/vt/termination/termination.h
- src/vt/termination/tree/epoch_tree.h
- tests/unit/scheduler/test_priority_queue.cc
This PR provides:
- A non-heuristic hang detector, only detects a hang iff it's impossible for the system to make progress
- Relies on work priorities, which provides a central queue
- Term messages are marked as such, and tracked by the schduler
- Two forms of "idleness" (term and non-term)
- Halt all progress on global epoch unless schedule is idle (minus term messages)
- Fixes a major performance bug in collective epochs
- Create a new API call for creating epoch dependencies (instead of simply a produce/consume), which carry the semantic of the dependency for optimization purposes
- Do not forward progress epochs that cannot finish due to a dependency
- Optimizes the structure of epoch graphs, eliding redundant dependencies
- If a hang is *detected*, abort and output a DOT file of the …
> 500 Non-heuristic termination hang detector, DOT epoch graphs, performance bugs

- src/vt/configs/arguments/args.cc
- src/vt/runtime/runtime.cc
#539, #544 caused color to *not* be output by default anymore on a my terminal (Mac). Restore the original logic (default on, not relying on `isatty`, unless `--vt_auto_color` is explicit to detect the termination type)
Fixes #556
> #556 restore the original coloring logic

- src/vt/registry/auto/auto_registry_common.h
- src/vt/registry/auto/auto_registry_general_impl.h
- Replace the T-lambda with a strong type-erased proxy.
This avoids signifcant T-cost.
Uses unique_ptr because shared_ptr is also T-costly.
(Working on find a middle-ground with C++ and type-erasure
as well.. Base + Proxy + Impl seems okay, if not verbose.)
> 537 eliminate T-lambda in Auto Registry

- src/vt/configs/arguments/args.cc
- src/vt/configs/arguments/args.h
- src/vt/runtime/runtime.cc
- src/vt/vrt/collection/balance/baselb/baselb.cc
- src/vt/vrt/collection/balance/baselb/baselb.h
- src/vt/vrt/collection/balance/gossiplb/gossiplb.cc
- src/vt/vrt/collection/balance/gossiplb/gossiplb.h
- src/vt/vrt/collection/balance/greedylb/greedylb.cc
- src/vt/vrt/collection/balance/greedylb/greedylb.h
- src/vt/vrt/collection/balance/hierarchicallb/hierlb.cc
- src/vt/vrt/collection/balance/hierarchicallb/hierlb.h
- src/vt/vrt/collection/balance/lb_invoke/invoke.cc
- src/vt/vrt/collection/balance/read_lb.cc
- src/vt/vrt/collection/balance/read_lb.h
- src/vt/vrt/collection/balance/rotatelb/rotatelb.cc
- src/vt/vrt/collection/balance/rotatelb/rotatelb.h
- tests/CMakeLists.txt
- tests/unit/lb/test_lb_reader.cc
The new file format allows for different parameters for each LB. Can be passed as a file or using `--vt_lb_args="c=1 k=5 f=2 i=10"`.
Example file:
```
%10 GossipLB c=1 k=5 f=2 i=10
0 HierarchicalLB min=0.9 max=1.1 auto=false
%5 GreedyLB min=1.0
120 GreedyLB c=0 k=2 f=3 i=3
```
Format:
```
[%] [iter] <LB-name> [key=value]...
```
Specific iteration lines override mods. Mods precedence is based on position in file, thus on iteration 10, `GreedyLB` will run---not `GossipLB`.
Fixes #561
> #561 implement new file spec with LB-specific params

- src/vt/messaging/active.cc
- src/vt/parameterization/parameterization.h
- src/vt/rdma/state/rdma_state.cc
- src/vt/registry/auto/auto_registry.cc
- src/vt/registry/auto/auto_registry.h
- src/vt/registry/auto/auto_registry_impl.h
- src/vt/registry/auto/auto_registry_interface.h
- src/vt/registry/auto/collection/auto_registry_collection.impl.h
- src/vt/runnable/collection.impl.h
- src/vt/runnable/general.impl.h
- src/vt/runnable/vrt.impl.h
- src/vt/trace/trace.cc
- src/vt/trace/trace.h
- src/vt/trace/trace_common.h
- src/vt/trace/trace_containers.cc
- src/vt/trace/trace_containers.h
- src/vt/trace/trace_event.cc
- src/vt/trace/trace_event.h
- src/vt/trace/trace_log.h
- src/vt/trace/trace_registry.cc
- src/vt/trace/trace_registry.h
"Works better". Pre-work to make #554 easier, as in 'not going to run into these issues'.
This will be part of #554 and as it contains trace-related bugs still.
- fixed (apparent?) initialization ordering issue where events add during initialization could not be found later in certain cases (differed by example project).
- fixed cross-access of iterators
- a bunch of updates for consistency, responsibility hiding, etc.
Fixes #575
> 575 event registry bugs

- src/vt/group/collective/group_info_collective.cc
Fixes #587 
Quick change for beta.4 to fix a new warning that popped up based on the last group refactor in beta.4
> #587 Fix warning with GNU compilers

- src/vt/runtime/runtime.cc
- src/vt/runtime/runtime.h
> #592 vtAbort if LB compile-time disabled but runtime enabled

- cmake/link_vt.cmake
- src/vt/configs/error/stack_out.cc
- Builds on Ubuntu now (not really sure *why* it was building on OS X - LD pulled in otherwise?)
- Split to stack_out.cc to reduce global VT pollution.
> 603 dladdr link

- src/vt/vrt/collection/manager.impl.h
- src/vt/vrt/collection/migrate/migrate_msg.h
- tests/unit/termination/test_term_dep_send_chain.cc
Fixes #597 
Migration leak showing up in EMPIRE. During de-serialization, a copy of `ColT` was not being deallocated properly, leaking during every migration.
> 597 migration leak

- src/vt/runtime/runtime.cc
- src/vt/runtime/runtime.h
- src/vt/termination/dijkstra-scholten/comm.cc
- src/vt/termination/dijkstra-scholten/comm.h
- src/vt/termination/dijkstra-scholten/ds.cc
- src/vt/termination/dijkstra-scholten/ds.h
- src/vt/termination/term_window.h
- src/vt/termination/termination.cc
- src/vt/termination/termination.h
- tests/unit/termination/test_term_cleanup.cc
> #621 Termination clear out state after term detected

- src/vt/registry/auto/auto_registry_general.h
- src/vt/utils/demangle/demangle.cc
- src/vt/utils/demangle/demangle.h
- Fixes bug where barenames outside of any namespace could have
leading characters removed.
- The "(none)" namespace placeholer is used for types that
do not belong to any namespace.
> #635 fix barename and namespace extraction

- tests/unit/termination/test_term_cleanup.cc
This can also be applied to 1.0.0-beta-5
> #668: signed vs unsigned warnings with gcc 9.2.0 in test_term_cleanup

- src/vt/trace/trace.cc
- src/vt/trace/trace.h
- Was incorrectly guarding 'event type' == 0, which CAN be true..
..even if it probably should be the case. Now guards against
the 'entry id' itself.
Fixes #680
> #680 fix trace guard

- src/CMakeLists.txt
- src/vt/configs/arguments/args.cc
- src/vt/configs/arguments/args.h
- src/vt/runtime/runtime.cc
- src/vt/runtime/runtime_holder.h
- src/vt/trace/file_spec/spec.cc
- src/vt/trace/file_spec/spec.h
- src/vt/trace/trace.cc
- src/vt/trace/trace.h
- src/vt/vrt/collection/balance/lb_invoke/invoke.cc
- src/vt/vrt/collection/balance/lb_invoke/invoke.h
- src/vt/vrt/collection/manager.impl.h
- tests/CMakeLists.txt
- tests/unit/trace/test_trace_spec_reader.cc
Fixes #689 
Adds a new tracing specification file to enabled traces based on patterns on the LB phase. Needed for large scale EMPIRE runs on Trinity
> 689 New tracing enable specification file

- src/vt/vrt/collection/balance/hierarchicallb/hierlb.cc
- src/vt/vrt/collection/balance/hierarchicallb/hierlb.h
- src/vt/vrt/collection/balance/read_lb.h
Note: I based this PR off of beta.5 instead of develop.
Add a string argument called `strategy` to the LB file entries for `HierarchicalLB` to control what value of `HeapExtractEnum` is passed to `calcLoadOver`. The accepted strings are the names of `HeapExtractEnum` values that have been implemented, which are currently `LoadOverLessThan` (default), `LoadOverGreaterThan`, and `LoadOverOneEach`. This option allows deviating from the default practice of preferring to migrate the smallest objects.
I have omitted `LoadOverRandom` because it doesn't appear to be implemented (and there did not appear to be any check that this value wasn't selected).  Please correct me if I am wrong.
Please let me know if you have suggestions for better strings to use.  I can see rephrasing to use something …
> 696 HierarchicalLB: Add strategy argument to LB file

- src/vt/termination/termination.cc
Fixes #694
This fixes a very occasional bug in termination DS that causes a segfault which is present on develop and beta.5
> 694 Fix termination segfault caused by TermDS being erased while running

- src/vt/messaging/dependent_send_chain.h
Fixes #710 
Unfortunately, the last fix to switch `nextStep` to using DS epochs by default missed a call in dependent send chain. This is a major problem for EMPIRE performance.
> 710 Termination: use DS-epoch by default in dep send chain

- examples/term_ds.cc
- src/vt/messaging/collection_chain_set.h
- src/vt/messaging/dependent_send_chain.h
- src/vt/termination/dijkstra-scholten/ds.h
- src/vt/termination/epoch_label.cc
- src/vt/termination/epoch_label.h
- src/vt/termination/epoch_tags.cc
- src/vt/termination/epoch_tags.h
- src/vt/termination/graph/epoch_graph.cc
- src/vt/termination/graph/epoch_graph.h
- src/vt/termination/term_state.h
- src/vt/termination/termination.cc
- src/vt/termination/termination.h
- src/vt/vrt/collection/balance/baselb/baselb.cc
- src/vt/vrt/collection/balance/gossiplb/gossiplb.cc
- src/vt/vrt/collection/manager.impl.h
- tests/unit/termination/test_term_cleanup.cc
- tests/unit/termination/test_term_dep_send_chain.cc
- tests/unit/termination/test_termination_action_common.impl.h
- tests/unit/termination/test_termination_action_nested_collect.cc
- tests/unit/termination/test_termination_action_nested_rooted.cc
Fixes #723 
Add a new optional parameter when creating a new epoch to specify a label that is dumped in debugging output (DOT files). In order to make this change correctly, a breaking change is made on non-default overloads of `TerminationDetector::makeEpochCollective` and `TerminationDetector::makeEpochRooted` due to char* to bool overload problems.
Thus, a tag class is used to specify/capture if the successor epoch should be the current epoch (or an manual override by the user) or whether a DS epoch should be used. This has the added benefit of making the interface more explicit and less error prone.
[outfile-global.pdf](https://github.com/DARMA-tasking/vt/files/4296367/outfile-global.pdf)
This has potential for beta.6, depending on feedback.
> 723 Add debugging epoch labels

- src/vt/vrt/collection/balance/proc_stats.cc
Fixes #695 
Fixes this warning:
```
/Users/jliffla/codes/vt/virtual-transport/src/vt/vrt/collection/balance/proc_stats.cc:147:66: warning: format specifies type 'unsigned long *' but the argument has type 'vt::vrt::collection::balance::ElementIDType *' (aka 'unsigned long long *') [-Wformat]
if (fscanf(pFile, "%zu %c %lu %c %lf", &phaseID, &separator, &elmID,
~~~                                ^~~~~~
%llu
1 warning generated.
```
> 695 LB fix warning in proc stats

- CMakeLists.txt
- cmake/check_system_functions.cmake
- cmake_config.h.in
- src/CMakeLists.txt
- src/vt/configs/arguments/args.cc
- src/vt/configs/arguments/args.h
- src/vt/runtime/runtime.cc
- src/vt/trace/trace.cc
- src/vt/trace/trace.h
- src/vt/trace/trace_log.h
- src/vt/utils/memory/memory_reporter.h
- src/vt/utils/memory/memory_units.cc
- src/vt/utils/memory/memory_units.h
- src/vt/utils/memory/memory_usage.cc
- src/vt/utils/memory/memory_usage.h
- src/vt/vrt/collection/balance/lb_invoke/invoke.cc
- src/vt/vrt/collection/balance/lb_invoke/invoke.h
- tests/CMakeLists.txt
- tests/perf/memory_checker.cc
There isn't a good general way to get memory usage across all platforms. Thus, I've added a host of methods for reporting memory usage that are protected by cmake system checks before they get enabled. The user can specify a precedence order for the memory reporters with the flag `--vt_memory_reporters`. The default order is `mstats,machinfo,selfstat,sbrk,mallinfo,getrusage,ps`.
Additionally, there is a flag for enabling memory usage prints after each phase 
`--vt_print_memory_each_phase` along with which node the user wants to be informed about 
`--vt_print_memory_node`. Those phase prints look something like this:
With all this in place, I now have a new option to trace memory usage also, enabled with the flag: 
`--vt_trace_memory_usage`. The highest priority working memory reporter …
> 726 Trace memory usage

- src/vt/rdmahandle/holder.impl.h
> 734 OpenMPI's MPI_Op is not printable (MPICH is int)

- src/vt/configs/arguments/args.cc
- src/vt/configs/arguments/args.h
- src/vt/runtime/runtime.cc
- src/vt/scheduler/scheduler.cc
- src/vt/scheduler/scheduler.h
- src/vt/utils/memory/memory_units.cc
- src/vt/utils/memory/memory_units.h
- src/vt/utils/memory/memory_usage.cc
- src/vt/utils/memory/memory_usage.h
- tests/perf/memory_checker.cc
Fixes #738 
In EMPIRE, @nlslatt and I realized that it would help to be able to see when memory usage crosses some threshold increment to track if memory usage is blowing up.
Add three new opt-in arguments:
* `--vt_print_memory_at_threshold` : enable prints at a memory threshold
* `--vt_print_memory_sched_poll=100` : check memory usage every 100 scheduler polls (certain memory reporters can be expensive so this gives control to the user)
* `--vt_print_memory_threshold="1.2 GiB"` : whenever the first memory usage reporter crosses an increment of 1.2 GiB (up or down), VT will print to screen the current usage
Prints look like this (run for ever 1 GiB):
```
vt: [0] general: Memory usage (+) mstats=1028.92 machinfo=1047.39 getrusage=1047.39 (MiB)
vt: [0] general: Memory usage (-) …
```
> 738 Print memory usage

- src/vt/messaging/active.h
- src/vt/trace/trace.cc
- src/vt/trace/trace.h
- src/vt/trace/trace_common.h
- src/vt/trace/trace_user.h
- src/vt/trace/trace_user_event.cc
- src/vt/trace/trace_user_event.h
- src/vt/vrt/collection/balance/lb_invoke/invoke.cc
- src/vt/vrt/collection/balance/lb_invoke/invoke.h
- src/vt/vrt/collection/manager.cc
> 721 Trace flush bug fixes

- src/vt/trace/trace.cc
- src/vt/vrt/collection/balance/proc_stats.cc
- Ensure types are fully compatible with the format specifier.
Some compilers check and generate warnings.
No warnings in GCC7/Clang5/ICC18 for VT or example builds.
> #647 fix format-string type warnings

- src/vt/messaging/active.cc
- src/vt/messaging/irecv_holder.h
> 774 irecv test right away

- src/vt/vrt/collection/balance/gossiplb/gossiplb.cc
- src/vt/vrt/collection/balance/gossiplb/gossiplb.h
Fixes #769 
- Fix broken CMF adding overloaded nodes
- Fix missing sync at iteration start causing load 0.0 to propagate
> 769 gossip bugs

- src/vt/vrt/collection/balance/elm_stats.cc
- src/vt/vrt/collection/balance/elm_stats.h
- src/vt/vrt/collection/balance/elm_stats.impl.h
This is sufficient API to see how it fits together with EMPIRE, I think.
To validate the changes all the way through, I'm going to add code on one side or the other to force consideration of only a single subphase's load when making LB decisions.
> #708 vector balancing, part 1

- src/vt/collective/collective_alg.cc
- src/vt/collective/collective_alg.h
- src/vt/collective/collective_scope.cc
- src/vt/collective/collective_scope.h
- src/vt/collective/reduce/reduce.h
- src/vt/collective/reduce/reduce.impl.h
- src/vt/runtime/runtime.cc
- tests/unit/collectives/test_mpi_collective.cc
Fixes #793 
Implement a new call to enqueue an MPI collective and run it safely **while** VT is running.
```C++
auto tag = vt::theCollective()->mpiCollective([]{
MPI_Barrier(MPI_COMM_WORLD);
});
vt::theCollective()->waitCollective(tag);
```
> 793 Safe MPI collectives

- src/vt/collective/collective_scope.cc
- src/vt/collective/reduce/operators/default_op.impl.h
- src/vt/group/collective/group_info_collective.cc
- src/vt/pipe/callback/proxy_send/callback_proxy_send.h
- src/vt/pipe/pipe_manager_tl.h
- src/vt/termination/termination.cc
- src/vt/vrt/collection/balance/lb_invoke/invoke.cc
- src/vt/vrt/collection/balance/proc_stats.util.h
- src/vt/vrt/collection/proxy.h
- src/vt/vrt/proxy/collection_proxy.h
- src/vt/vrt/proxy/collection_proxy.impl.h
The final include cleanup was necessary to make this API possible. The earlier ones got some distractions out of the way so I could find the solution.
> Add subphase setting API for application callers

- src/vt/context/context.cc
- src/vt/group/collective/group_info_collective.cc
- src/vt/group/group_manager.cc
- src/vt/group/group_manager.h
- src/vt/rdma/channel/rdma_channel.cc
- src/vt/rdma/rdma.cc
- src/vt/rdma/rdma.h
- src/vt/rdmahandle/manager.cc
- src/vt/rdmahandle/manager.h
- src/vt/rdmahandle/manager.impl.h
- src/vt/runtime/runtime.cc
> 816 Use safe MPI collective API for all blocking MPI calls

- src/vt/vrt/collection/collection_directory.h
- src/vt/vrt/collection/manager.h
- src/vt/vrt/collection/manager.impl.h
- src/vt/vrt/collection/staged_token/token.h
- tests/unit/collection/test_checkpoint.cc
Fixes #808 
Has a test, working.
> 808 Checkpoint/Restart collection

- tests/unit/runtime/test_mpi_access_guards.cc
Fixes #835
Debug, flag enabled (default):
```
[       OK ] TestMpiAccessGuardDeathTest.test_mpi_access_prevented (109 ms)
[       OK ] TestMpiAccessGuardTest.test_mpi_access_allowed (1 ms)
```
Release, flag enabled (forced); same if flag-disabled in any build:
```
[  SKIPPED ] TestMpiAccessGuardDeathTest.test_mpi_access_prevented (54 ms)
[       OK ] TestMpiAccessGuardTest.test_mpi_access_allowed (1 ms)
```
> #835 skip MPI guard positive test in release builds

- src/CMakeLists.txt
- src/vt/vrt/collection/balance/lb_invoke/invoke.cc
- src/vt/vrt/collection/balance/lb_type.h
- src/vt/vrt/collection/balance/randomlb/randomlb.cc
- src/vt/vrt/collection/balance/randomlb/randomlb.h
Fixes #831 
New load balancer for testing---RandomLB. It can be explicitly seeded or randomized using C++'s `std::random_device`:
- Seeding: `--vt_lb --vt_lb_name="RandomLB" --vt_lb_args="seed=1024"`
- Randomizing:  `--vt_lb --vt_lb_name="RandomLB" --vt_lb_args="randomize_seed=true"`
> 831 Implement RandomLB

- ci/test_cpp.sh
- cmake/define_build_types.cmake
- src/vt/collective/basic.cc
- src/vt/serialization/messaging/serialized_messenger.impl.h
- src/vt/vrt/collection/manager.impl.h
- src/vt/vrt/proxy/base_collection_elm_proxy.h
- src/vt/worker/worker_group.impl.h
Fixes #840 
Solve a bad lifetime access and a memory leak. #842 will be a more principled solution to the leak.
TODO:
> 840 Fix asan issues and CI issues with return code

- src/vt/vrt/collection/manager.h
- src/vt/vrt/collection/manager.impl.h
- src/vt/vrt/collection/messages/system_create.h
- src/vt/vrt/collection/op_buffer.h
Fixes #713 
Fixes a non-deterministic bug in running the tutorial with group creation racing with other setup processes. 
Rewrite the collection buffering code to be more consistent
This fixes the bug after running the `tutorial` thousands of times without failure with these changes.
> 713 Rewrite buffering code in collection manager to fix bugs

- src/vt/pmpi/generate_mpi_wrappers.pl
- This better integrates with some usage applications.
The change is to use traditional-style perl parameters.
> #850 Downgrade perl dependency to 5.16.3 (affected MPI guard-enabled builds)

- src/vt/configs/arguments/args.cc
- src/vt/configs/arguments/args.h
- src/vt/runtime/runtime.cc
- src/vt/runtime/runtime_banner.cc
Fixes #856 
Allows inputting/outputting config files for easier reproducibility and debugging. Exports the entire config with `--vt_output_config`. Config can be imported with `--vt_input_config`.
> 856 Args: CLI I/O config files

- src/vt/pipe/pipe_manager_base.cc
- src/vt/pipe/pipe_manager_base.h
- src/vt/pipe/pipe_manager_base.impl.h
- src/vt/pipe/signal/signal_holder.cc
- src/vt/pipe/signal/signal_holder.h
- src/vt/pipe/signal/signal_holder.impl.h
- tests/unit/pipe/test_signal_cleanup.cc
Fixes #794 
Fixes a bug discovered when writing safe MPI collective code. If the VT runtime is finalized, the pipe IDs are reset (used to identify a callback instance). But, the signal holder, which is a templated static container are not reset. Thus, the old registered listeners get triggered causing all sort of havoc. This was especially disturbing with testing, but many gtest tests run multiple tests in the same harness instance in one execution finalizing the VT runtime in between tests.
This also indicates that we probably need to audit all static (especially templated) data that is used in the runtime. There may be other static/global instances that would cause problems across finalizations or if VT is initialized twice (only halfway supported).
> 794 Fix signal holder cleanup bug

- src/vt/runtime/runtime.cc
- src/vt/scheduler/scheduler.cc
- src/vt/scheduler/scheduler.h
- src/vt/trace/trace.cc
- src/vt/trace/trace.h
- src/vt/trace/trace_user.h
All code that (consistently) uses `runSchedulerWhile` will emit events "between" such top-level loops. This also includes time between the last `runSchedulerWhile` and when the scheduler is finalized.
The red processing events on node 0 are time spent between the calls to `runSchedulerWhile` which is called via `runInEpoch*` (an artificial delay has been added). Node 1 jumps directly to vt::finalize and thus does not have (much) time "between" top-level schedulers.
These changes should be matched in all client usages to never call `runScheduler` directly. This is because a 'between' event may remain on the open event stack until the next call to `runSchedulerWhile` or VT finalization.
--
Using user events (older commits):
Fixes #845
> #845 Log events 'between' top-level schedulers; can cover when VT is not running.

- src/vt/trace/trace_common.h
> EMPIRE/TPL/vt/src/vt/trace/trace_common.h(59): warning: integer conversion resulted in a change of sign
> Fix nvcc warning about sign mismatch

- src/vt/scheduler/scheduler.cc
- src/vt/scheduler/scheduler.h
- src/vt/trace/trace.cc
- src/vt/trace/trace.h
- src/vt/trace/trace_user.h
Ported to beta.9 branch.
**Note**: this _may_ fail in code that uses manual scheduler loops (not using `runSchedulerWhile`) when tracing is enabled if begin/end processing events are intertwined. All client code should be updated to use `runSchedulerWhile` for 'guaranteed' pairings.
It might be useful to accept the other scheduler-loop constructs into beta9, if such makes implementation easier.
> 854 - Outside Scheduler Loop Events

- src/vt/messaging/active.cc
- Iprobe and Test were not guarded..
`mpirun -n 8  ./examples/collection/lb_iter --vt_lb --vt_lb_name=GossipLB`
> 886 - Add missing MPI-allowed guard in recvDataMsgBuffer

- src/vt/pmpi/generate_mpi_wrappers.pl
Much simpler than first expect..
Simply adding some exclusions for OpenMPI 1.10 compatibility.
Hoping messages in #867 are complete.
> 867 - Exclude PMPI calls for OpenMPI 1.10 compatibility

- src/vt/utils/adt/union.h
- tests/unit/utils/test_safe_union.cc
Fixes #922 
Another spin off of #882, that provides a lot more safety when switching.
> 922 Implement static type switch on safe union

- src/vt/pmpi/generate_mpi_wrappers.pl
> #927: Don't use vtAssert in MPI access guards

- cmake-modules/CheckLinkerFlag.cmake
- cmake/set_linker_flags.cmake
- src/CMakeLists.txt
> 914 Fix stacktrace symbols when dladdr fails

- ci/build_cpp.sh
- cmake/turn_on_warnings.cmake
- src/vt/messaging/active.impl.h
- src/vt/messaging/message/message_serialize.h
- src/vt/rdmahandle/manager.impl.h
- tests/perf/ping_pong.cc
- tests/unit/pool/test_pool_message_sizes.cc
Something broke with https://github.com/DARMA-tasking/vt/pull/911 and it stopped tracking new commits. This might have been related to the subsequent GitHub outage.. created a new PR in any case.
---
Fixes several NVCC issues to get compilation to work in 10.1 and 11 NVCC/Cuda compilers.
Build has outstanding issue of supplying both "-std=C++1y" and "std=C++14" options at the same time. This raises warnings in NVCC, although it should be operating in C++14 mode.
Fixes: #908
> 908 - fix NVCC issues (mostly around serialization)

- .github/workflows/dockerimage-intel-18-ubuntu-mpich-extended.yml
- .github/workflows/dockerimage-nvidia-10-ubuntu-mpich-extended.yml
- .github/workflows/dockerimage-nvidia-10-ubuntu-mpich.yml
- .github/workflows/dockerimage-nvidia-11-ubuntu-mpich-extended.yml
- .github/workflows/dockerimage-nvidia-11-ubuntu-mpich.yml
- README.md
- ci/build_cpp.sh
- ci/docker/ubuntu-18.04-nvidia-cpp.dockerfile
- cmake/turn_on_warnings.cmake
- docker-compose.yml
- docs/md/building.md
- scripts/workflows.ini
- src/vt/messaging/active.impl.h
- src/vt/messaging/message/message_serialize.h
- src/vt/rdmahandle/handle.index.impl.h
- src/vt/rdmahandle/handle.node.impl.h
- src/vt/rdmahandle/manager.impl.h
- tests/perf/ping_pong.cc
- tests/unit/pool/test_pool_message_sizes.cc
> 904 Add nvcc (cuda) to CI

- docs/md/node-stats.md
- docs/md/vt.md
- src/vt/runtime/runtime.cc
- src/vt/runtime/runtime.h
- src/vt/runtime/runtime_component_fwd.h
- src/vt/runtime/runtime_get.cc
- src/vt/vrt/collection/balance/baselb/baselb.cc
- src/vt/vrt/collection/balance/baselb/baselb.h
- src/vt/vrt/collection/balance/elm_stats.impl.h
- src/vt/vrt/collection/balance/lb_invoke/lb_manager.cc
- src/vt/vrt/collection/balance/model/load_model.h
- src/vt/vrt/collection/balance/model/per_collection.cc
- src/vt/vrt/collection/balance/model/raw_data.h
- src/vt/vrt/collection/balance/node_stats.cc
- src/vt/vrt/collection/balance/node_stats.h
- src/vt/vrt/collection/balance/stats_msg.h
- src/vt/vrt/collection/balance/statsmaplb/statsmaplb.cc
- src/vt/vrt/collection/manager.cc
- src/vt/vrt/collection/manager.impl.h
- src/vt/vrt/collection/types/migratable.cc
- src/vt/vrt/collection/types/migratable.h
- tests/unit/lb/test_lb_stats_reader.cc
Changes: 
- Rename ProcStats structure to NodeStats (file name changed as well)
- **Rename ProcStatsMsg to NodeStatsMsg ( I assumed by the name of structure that it's related to ProcStats, so i changed it for consistency )**
- Rename all member functions/variables so that they refer to 'node' instead of 'process'
- Update docs
>  #870: Change name of component ProcStats to NodeStats for consistency

- src/vt/pmpi/generate_mpi_wrappers.pl
Some systems don't have this module. Removed.
> 964 - Remove autodie module usages from PMPI generator script

- docs/md/scheduler.md
- src/vt/scheduler/scheduler.h
- tests/unit/group/test_group.cc
- tests/unit/location/test_hops.extended.cc
- tests/unit/location/test_location_common.h
- tests/unit/memory/test_memory_lifetime.cc
- tests/unit/objgroup/test_objgroup.cc
- tests/unit/pipe/test_callback_bcast.cc
> 955 clear out uses of addAction in tests

- src/vt/vrt/collection/proxy_traits/proxy_elm_traits.h
- src/vt/vrt/proxy/base_collection_elm_proxy.h
- src/vt/vrt/proxy/base_collection_elm_proxy.impl.h
- src/vt/vrt/proxy/base_elm_proxy.h
- src/vt/vrt/proxy/collection_elm_proxy.h
- src/vt/vrt/proxy/collection_proxy.impl.h
- src/vt/vrt/proxy/collection_proxy_untyped.impl.h
> 939 de-template BaseElmProxy over ColT

- src/vt/collective/scatter/scatter.cc
- src/vt/collective/tree/tree.cc
- src/vt/collective/tree/tree.h
rename the method and update the docs
Fixes #884
> 884 rename getNumTotalChildren to getNumDescendants

- src/vt/collective/collective_alg.cc
- src/vt/collective/collective_scope.cc
- src/vt/collective/collective_scope.h
> #986: Run MPI collectives as part of active epoch at initial call

- tests/unit/location/test_location_common.h
- tests/unit/pipe/test_callback_bcast_collection.extended.cc
remove remaining usage of addAction from:
`tests/unit/pipe/test_callback_bcast_collection.extended.cc`
`tests/unit/location/test_location_common.h`
> 955 clear out uses of addAction from tests

- src/CMakeLists.txt
- src/vt/collective/reduce/reduce.h
- src/vt/collective/reduce/reduce.impl.h
- src/vt/messaging/collection_chain_set.h
- src/vt/messaging/dependent_send_chain.h
- src/vt/messaging/pending_send.cc
- src/vt/messaging/pending_send.h
- src/vt/objgroup/manager.h
- src/vt/objgroup/manager.impl.h
- src/vt/objgroup/proxy/proxy_objgroup.h
- src/vt/objgroup/proxy/proxy_objgroup.impl.h
- src/vt/vrt/collection/manager.h
- src/vt/vrt/collection/manager.impl.h
- src/vt/vrt/collection/reducable/reducable.h
- src/vt/vrt/collection/reducable/reducable.impl.h
- tests/unit/termination/test_term_chaining.cc
- tests/unit/termination/test_term_dep_send_chain.cc
> 702 make reduce return pending send

- src/vt/vrt/collection/manager.h
- src/vt/vrt/collection/manager.impl.h
- src/vt/vrt/collection/staged_token/token.h
- src/vt/vrt/collection/staged_token/token.impl.h
- tests/unit/collection/test_checkpoint.extended.cc
Fixes #1007
- Write a test that triggers the destruction bug
- Add missing cleanup functions (destroy not working) for token-based collection insertion
- Refactor to avoid calling both copy constructor and move constructor when restoring from file
- Create a helper for doing the insertion once the unique pointer is available
> 1007 Add missing cleanup for restoreFromFile

- examples/group/group_collective.cc
- src/vt/group/group_manager.cc
- src/vt/group/group_manager.h
- src/vt/group/group_manager.impl.h
- src/vt/vrt/collection/manager.impl.h
- tests/unit/group/test_group.cc
> 878 Cleanup group manager interfaces

- src/vt/vrt/collection/balance/lb_invoke/lb_manager.cc
- src/vt/vrt/collection/balance/model/comm_overhead.cc
- src/vt/vrt/collection/balance/model/comm_overhead.h
- src/vt/vrt/collection/balance/model/composed_model.cc
- src/vt/vrt/collection/balance/model/composed_model.h
- src/vt/vrt/collection/balance/model/linear_model.cc
- src/vt/vrt/collection/balance/model/linear_model.h
- src/vt/vrt/collection/balance/model/load_model.h
- src/vt/vrt/collection/balance/model/naive_persistence.cc
- src/vt/vrt/collection/balance/model/naive_persistence.h
- src/vt/vrt/collection/balance/model/norm.cc
- src/vt/vrt/collection/balance/model/per_collection.cc
- src/vt/vrt/collection/balance/model/per_collection.h
- src/vt/vrt/collection/balance/model/persistence_median_last_n.cc
- src/vt/vrt/collection/balance/model/persistence_median_last_n.h
- src/vt/vrt/collection/balance/model/raw_data.cc
- src/vt/vrt/collection/balance/model/raw_data.h
- src/vt/vrt/collection/balance/node_stats.cc
- src/vt/vrt/collection/balance/node_stats.h
- tests/unit/collection/test_model_linear_model.nompi.cc
- tests/unit/collection/test_model_multiple_phases.nompi.cc
- tests/unit/collection/test_model_naive_persistence.nompi.cc
- tests/unit/collection/test_model_per_collection.extended.cc
- tests/unit/collection/test_model_persistence_median_last_n.nompi.cc
- tests/unit/collection/test_model_raw_data.nompi.cc
> #991: LoadModel: Add API to calculate how many phases of past load data need to be kept

- examples/callback/callback_context.cc
- src/vt/pipe/callback/proxy_bcast/callback_proxy_bcast_tl.impl.h
- src/vt/pipe/pipe_lifetime.h
- src/vt/pipe/pipe_manager.h
- src/vt/pipe/pipe_manager.impl.h
- src/vt/pipe/pipe_manager_tl.h
- src/vt/pipe/pipe_manager_tl.impl.h
- src/vt/rdma/rdma.cc
- tests/unit/memory/test_memory_lifetime.cc
- tests/unit/pipe/test_callback_func.cc
- tests/unit/pipe/test_callback_func_ctx.cc
- tests/unit/pipe/test_signal_cleanup.cc
- tutorial/tutorial_1g.h
Fixes #1020
This address 95% of the problems with callbacks:
- Fix useless state that was building up
- Reroute collection bcast callback always through the virtual dispatcher to eliminate required state
- Change `makeFunc` to have a lifetime associated so it gets deleted if it one-time use
> 1020 Fix callback lifetime

- tests/unit/pipe/test_callback_bcast_collection.extended.cc
- tests/unit/pipe/test_callback_send_collection.extended.cc
Fixes #1004 
Create collection on single node in TestCallbackSendCollection and TestCallbackBcastCollection in order to prevent CI failing on some build configs.
> 1004 Create collection on single node in TestCallbackSendCollection and TestCallbackBcastCollection

- tests/unit/collection/test_model_comm_overhead.nompi.cc
- tests/unit/collection/test_model_norm.nompi.cc
- tests/unit/collection/test_model_select_subphases.nompi.cc
Fixes #959 
Part 2 of adding unit tests for load models (part 1 -> https://github.com/DARMA-tasking/vt/pull/1001)
Add unit tests for following load models:
> 959 Add some more tests for various load models (Part 2)

- src/vt/objgroup/manager.impl.h
Fixes #1040 
Another memory leak down, leaked as EMPIRE is running LB each timestep
Green line-- with the fix
Red line--w/o the fix
[stria-8color-pipe-beta.10.1-objgroup.mallinfo.pdf](https://github.com/DARMA-tasking/vt/files/5205357/stria-8color-pipe-beta.10.1-objgroup.mallinfo.pdf)
.
> 1040 Fix objgroup leak in base registration code

- .github/workflows/dockerimage-gcc-5-ubuntu-mpich.yml
- scripts/workflows.ini
- tests/unit/active/test_active_send.cc
- tests/unit/active/test_pending_send.cc
- tests/unit/collection/test_checkpoint.extended.cc
- tests/unit/collection/test_destroy.cc
- tests/unit/collection/test_insert.extended.cc
- tests/unit/collectives/test_mpi_collective.cc
@PhilMiller @lifflander 
There should be some discussion about the test case test_pending_send.cc. That is a special case and was not amenable to the typical case of removing add action and placing runInEpochCollective. Jonathan and I had a call on Sunday to discuss the implementation in this request. The issue is that the runInEpochCollective has no support for actions that are emplaced for execution later. Instead it just runs a unit of work and moves on. That does not work in the test_pending_send case as it is a sort of prepare and wait sort of send instead of send at the immediate moment.
> #955 clear out uses of addAction in tests

- src/vt/runtime/runtime.cc
- src/vt/runtime/runtime.h
- tests/unit/pipe/test_signal_cleanup.cc
> 1002 Add option to disable signal handlers in vt::finalize

- .github/workflows/check-pr-comment-fixes-issue.yml
Fixes #1031
Most of the work is done in DARMA-tasking/check-pr-fixes-issue#1
The action is run every time the PR title or description (PR's first comment) is edited, and after opening and reopening the PR. If you want to play with it by yourself feel free to check this PR -> jstrzebonski/action_test#9 to not litter this PR anymore.
> 1031 add action to check PR's description format

- src/vt/collective/reduce/reduce.h
- src/vt/collective/reduce/reduce.impl.h
- src/vt/collective/reduce/reduce_manager.h
- src/vt/collective/reduce/reduce_manager.impl.h
- src/vt/group/collective/group_info_collective.cc
- src/vt/messaging/active.cc
- src/vt/messaging/active.h
- src/vt/messaging/active.impl.h
- src/vt/messaging/envelope/envelope_base.h
- src/vt/messaging/envelope/envelope_set.h
- src/vt/messaging/envelope/envelope_set.impl.h
- src/vt/messaging/envelope/envelope_setup.h
- src/vt/messaging/envelope/envelope_setup.impl.h
- src/vt/messaging/envelope/envelope_test.h
- src/vt/messaging/envelope/envelope_test.impl.h
- src/vt/messaging/pending_send.h
- src/vt/serialization/messaging/serialized_messenger.impl.h
- src/vt/vrt/collection/manager.impl.h
- tests/unit/active/test_active_broadcast.cc
- tests/unit/active/test_active_send.cc
- tests/unit/serialization/test_serialize_messenger.cc
Note: will rebase on 962 merge.
A message envelope is marked as "locked" on a send (this state is also carried through transmission).
A locked message cannot have certain envelope properties updated and will fail a vtAssert if this is not true. This prevents code from sending the same message multiple times. If a handler wishes to send a message it receives it must explicitly unlock the message (this is not expected to be common).
There is no protection against the content of a message being modified - no `const` is carried through (from a handler argument or otherwise). Although, perhaps handlers can elect to be const..
The main entry to handlers (receiving a message) must ensure to capture all envelope state prior to passing such down if it's required later. There are few touch-points …
> #1016 - Message Envelope Locking

- .github/workflows/check-pr-comment-fixes-issue.yml
Fixes #1075
The check should run when edited now! The default set is:
> By default, a workflow only runs when a pull_request_target's activity type is opened, synchronize, or reopened. To trigger workflows for more activity types, use the types keyword. For more information, see "Workflow syntax for GitHub Actions."
Removing the set made it not run on `edited`. This should fix the problem
> 1075 Run PR description when edited

- src/vt/vrt/collection/balance/node_stats.cc
> 1054 Fix inadvertently tautological comparison

- cmake-modules/SetCXXCompilerFlags.cmake
> #1088: Always use -std=c++14 for GCC and not earlier experimental -std=c++1y

- src/vt/collective/collective_alg.cc
- src/vt/collective/collective_alg.h
- src/vt/collective/collective_scope.cc
- src/vt/collective/collective_scope.h
- tests/unit/collectives/test_mpi_collective.cc
Fixes #1094
- There's a race between the de-allocation of a scope (when it goes out of scope) and the completion of the work. If the work completes before it goes out of scope it doesn't erase
- There's a bug in the scope when it's moved causing double de-allocation if it goes out of scope before completion of work
- Add tests that expose these bugs and then fix them
> 1094 Fix collective scope de-allocation

- src/vt/vrt/collection/balance/model/composed_model.cc
- src/vt/vrt/collection/balance/model/composed_model.h
- src/vt/vrt/collection/balance/model/linear_model.cc
- src/vt/vrt/collection/balance/model/linear_model.h
- src/vt/vrt/collection/balance/model/load_model.h
- src/vt/vrt/collection/balance/model/naive_persistence.cc
- src/vt/vrt/collection/balance/model/naive_persistence.h
- src/vt/vrt/collection/balance/model/per_collection.cc
- src/vt/vrt/collection/balance/model/per_collection.h
- src/vt/vrt/collection/balance/model/persistence_median_last_n.cc
- src/vt/vrt/collection/balance/model/persistence_median_last_n.h
- src/vt/vrt/collection/balance/model/raw_data.cc
- src/vt/vrt/collection/balance/model/raw_data.h
- src/vt/vrt/collection/balance/node_stats.cc
- src/vt/vrt/collection/balance/node_stats.h
- tests/unit/collection/test_model_comm_overhead.nompi.cc
- tests/unit/collection/test_model_linear_model.nompi.cc
- tests/unit/collection/test_model_multiple_phases.nompi.cc
- tests/unit/collection/test_model_naive_persistence.nompi.cc
- tests/unit/collection/test_model_norm.nompi.cc
- tests/unit/collection/test_model_persistence_median_last_n.nompi.cc
- tests/unit/collection/test_model_select_subphases.nompi.cc
> #1099: Count phases as unsigned and avoid mixed arithmetic/comparisons

- src/vt/collective/collective_ops.cc
- src/vt/configs/arguments/app_config.h
- src/vt/configs/arguments/args.cc
- src/vt/context/context.cc
- src/vt/context/context.h
- src/vt/runtime/runtime.cc
- src/vt/runtime/runtime.h
- src/vt/runtime/runtime_banner.cc
Don't crash processes by attempting to improperly call MPI_Init again.
Will still terminate a process, with diagnostic message, when there are invalid VT args. Invalid args are limited to those in the form `--vt_bad`.
Also moved any MPI_Init (when not interop) into the Runtime class itself, for parity with MPI_Finalize, full reliance on MPI_Init eating its own arguments, and some future update work.
Minor breaking: `--vt_mpi_args` is redundant and no longer supported.
fixes #1069
> #1069 runtime - don't re-initialize MPI in interop mode

- src/vt/context/context.cc
- src/vt/context/context.h
- src/vt/group/collective/group_info_collective.cc
- src/vt/group/collective/group_info_collective.h
- src/vt/group/group_info.cc
- src/vt/group/group_info.h
- src/vt/group/group_manager.cc
- src/vt/group/group_manager.h
- src/vt/rdmahandle/holder.impl.h
- src/vt/runtime/component/component_pack.cc
- src/vt/runtime/component/component_pack.h
- src/vt/runtime/component/component_pack.impl.h
- src/vt/runtime/runtime.cc
- src/vt/runtime/runtime.h
- tests/unit/test_parallel_harness.h
Increases uniformity of communicator lifetimes and ensures that all VT constructs are limited to the supplied communicator.
Previously, various constructs could apply the MPI_COMM_WORLD, even under an 'interop' mode.
Some of these commits are from #1069 which is expected to be merged first.
fixes #1092
> 1092 - Use communicator given to VT Runtime; don't assume MPI_COMM_WORLD

- .github/workflows/dockerimage-clang-3.9-ubuntu-mpich.yml
- .github/workflows/dockerimage-clang-5.0-ubuntu-mpich.yml
- .github/workflows/dockerimage-clang-8-alpine-mpich.yml
- .github/workflows/dockerimage-gcc-10-ubuntu-openmpi.yml
- .github/workflows/dockerimage-gcc-5-ubuntu-mpich.yml
- .github/workflows/dockerimage-gcc-6-ubuntu-mpich.yml
- .github/workflows/dockerimage-gcc-7-ubuntu-mpich.yml
- .github/workflows/dockerimage-gcc-8-ubuntu-mpich.yml
- .github/workflows/dockerimage-gcc-9-ubuntu-mpich.yml
- .github/workflows/dockerimage-intel-18-ubuntu-mpich-extended.yml
- .github/workflows/dockerimage-intel-18-ubuntu-mpich.yml
- .github/workflows/dockerimage-nvidia-10-ubuntu-mpich-extended.yml
- .github/workflows/dockerimage-nvidia-10-ubuntu-mpich.yml
- .github/workflows/dockerimage-nvidia-11-ubuntu-mpich-extended.yml
- .github/workflows/dockerimage-nvidia-11-ubuntu-mpich.yml
- ci/build_cpp.sh
- cmake/define_build_types.cmake
- cmake_config.h.in
- docker-compose.yml
- scripts/workflow-template.yml
- scripts/workflows.ini
- src/vt/configs/features/features_defines.h
Added new flag `vt_ci_build` to distinguish CI build from normal one. By default this only affects CI runs, meaning that if VT is built in Release mode locally (via docker containter or cmake) this will still have `production` flag set on.
Also, I think having the option to check for build type in the code can be useful in future (i.e. for unit tests we might want different behaviour in CI and different locally). So now you can check for CI build using `vt_check_enabled(ci_build)`
Fixes #1098
> 1098 Enable assertions during CI when release builds are used

- src/vt/vrt/collection/balance/elm_stats.cc
- src/vt/vrt/collection/balance/elm_stats.h
- src/vt/vrt/collection/balance/elm_stats.impl.h
- src/vt/vrt/collection/balance/node_stats.cc
- src/vt/vrt/collection/balance/node_stats.h
fixes #941 implementing subphases in loadComm
> #941 added subphase support to loadComm

- src/vt/scheduler/scheduler.cc
- src/vt/scheduler/scheduler.h
- src/vt/scheduler/scheduler.impl.h
- tests/unit/scheduler/test_high_level_calls.cc
> 1125 scheduler: template runInEpoch* functions 

- src/vt/configs/arguments/app_config.h
- src/vt/configs/arguments/args.cc
- src/vt/configs/arguments/args.h
- src/vt/configs/types/types_type.h
- src/vt/messaging/active.cc
- src/vt/messaging/active.h
- src/vt/messaging/irecv_holder.h
- src/vt/messaging/multitag_holder.h
- src/vt/messaging/send_info.h
- src/vt/rdma/collection/rdma_collection.cc
- src/vt/rdma/rdma.cc
- src/vt/rdma/rdma_msg.h
- src/vt/runtime/runtime_banner.cc
- src/vt/serialization/messaging/serialized_data_msg.h
- src/vt/serialization/messaging/serialized_messenger.impl.h
- src/vt/utils/memory/memory_units.cc
- src/vt/utils/memory/memory_units.h
- tests/unit/active/test_active_send_large.cc
Fixes #1111 
- Start with tests that fail for serialized/non-serialized messages
- ~Make a **major** improvement to how tests are being dispatched. Currently, tests are being ignored due to deficiencies in the gtest cmake. Pull in the latest gtest cmake and fix the bugs in that version of the cmake. **This is causing "new" tests to fail on this PR that weren't running before which I am systematically trying to fix**~
- Addressed & merged in separate PR
- Implement "multi-sends" for serialized and non-serialized messages (now passing!)
- Add a new runtime argument `--vt_max_mpi_send_size=X` that defaults to `1ull << 30`.
- Use the new argument injector to set the size for testing to `16384` bytes
> 1111 Fix for large message sends

- src/vt/vrt/collection/balance/elm_stats.cc
- src/vt/vrt/collection/balance/elm_stats.h
- src/vt/vrt/collection/balance/elm_stats.impl.h
- tests/unit/collection/test_lbstats_retention.cc
The vectors holding stats in ElementStats grow without bound.  This PR erases stats data for phases older than the lookback.
Fixes #1122
> 1122 elementstats is leaking

- src/vt/vrt/collection/balance/node_stats.cc
Subphase comm data in NodeStats for phases earlier than the lookback was not being cleared out in startIterCleanup as it was for other data structures.  This PR adds it, preventing the memory use from growing without bound.
Fixes #1154
> 1154 NodeStats subphase comm data growth

- ci/azure/azure-intel-19-ubuntu-mpich.yml
- scripts/workflows-azure.ini
- src/vt/collective/reduce/reduce.h
- src/vt/objgroup/proxy/proxy_objgroup.h
- src/vt/vrt/collection/reducable/reducable.h
- tests/unit/active/test_active_send_large.cc
- tests/unit/test_parallel_harness.h
>  #728: Avoid ICEs and compilation failures in Intel 19.x and Nvidia with gcc<=7.2.0

- src/vt/vrt/collection/balance/zoltanlb/zoltanlb.cc
> 1157: Use non deprecated send function for objgrp proxy in Zoltanlb

- cmake/local_package.cmake
Fixes #1159.
I made the same change here as in checkpoint.  This one doesn't get directly tested because vt is currently using checkpoint's `find_package_local`, as described in #1158.
> #1159: build: correct messages when package not found

- src/CMakeLists.txt
- src/vt/objgroup/manager.fwd.h
- src/vt/objgroup/manager.h
- src/vt/objgroup/manager.impl.h
- src/vt/objgroup/manager.static.h
- src/vt/objgroup/proxy/proxy_objgroup_elm.h
- src/vt/objgroup/proxy/proxy_objgroup_elm.impl.h
- src/vt/runnable/invoke.h
- src/vt/trace/trace.cc
- src/vt/trace/trace.h
- src/vt/trace/trace_constants.h
- src/vt/utils/static_checks/function_ret_check.h
- src/vt/vrt/collection/balance/lb_comm.h
- src/vt/vrt/collection/balance/node_stats.cc
- src/vt/vrt/collection/invoke/invokable.h
- src/vt/vrt/collection/invoke/invokable.impl.h
- src/vt/vrt/collection/manager.h
- src/vt/vrt/collection/manager.impl.h
- tests/unit/collection/test_invoke.cc
- tests/unit/objgroup/test_objgroup.cc
- tests/unit/objgroup/test_objgroup_common.h
- tests/unit/runnable/test_invoke.cc
> 1051: Add local invoke to proxies that trace and record LB

- src/vt/vrt/collection/balance/elm_stats.cc
- src/vt/vrt/collection/balance/elm_stats.h
- src/vt/vrt/collection/manager.h
- src/vt/vrt/collection/manager.impl.h
- tests/unit/collection/test_checkpoint.extended.cc
fixes #1183 
from discussion with Jonathan:
> If we assume that `theCollection()->restoreFromFile()` always is after a reinitialization of VT we can just set the phase in every element to 0 instead of deserializing it from file and getting the old phase (a true restart)
> The phase in `ElementStats` (embedded in the collection) needs to align with the user’s call to `theCollection()->nextPhase(proxy, phase)` so I think resetting it to zero is fine. Even if a full restart isn’t done, the user should just pass 0 to `nextPhase` since it was restored
> 1183 reset the phase when restoring from file

- .github/workflows/macosx-clang-mpich.yml
- ci/Brewfile
> #1190: Add a web-updatable 'secret' to the cache key, to ease dropping a broken cache

- examples/collection/transpose.cc
- lib/libfort/CMakeLists.txt
- src/vt/runtime/runtime_get.cc
- src/vt/scheduler/scheduler.cc
- tests/unit/termination/test_term_dep_send_chain.cc
Fixes #456
Current warnings: 
- /vt/src/vt/scheduler/scheduler.cc(340): warning #2557: comparison between signed and unsigned operands
- /vt/src/vt/scheduler/scheduler.cc(357): warning #2557: comparison between signed and unsigned operands
- /vt/src/vt/scheduler/scheduler.cc(366): warning #2557: comparison between signed and unsigned operands
- /vt/src/vt/runtime/runtime_get.cc(168): warning #3280: declaration hides variable "vt::rt" (declared at line 72 of "/vt/src/vt/runtime/runtime_inst.h")
- /vt/examples/collection/transpose.cc(213): warning #3868: declaration hides member "SubSolveInfo::sub_comm" (declared at line 124) in same scope
- /vt/tests/unit/termination/test_term_dep_send_chain.cc(527): warning #3280: declaration hides member "vt::vrt::VrtBase::proxy_" (declared at line 73 of …
> 456: Fix intel compile warnings

- src/vt/collective/startup.cc
- src/vt/collective/startup.h
- tests/unit/runtime/test_initialization.cc
> 1195: passing argc and argv by value causes incorrect argument parsing

- tests/unit/active/test_active_send_large.cc
- tests/unit/test_harness.h
- tests/unit/test_parallel_harness.h
> 1199: argv is missing nullptr at the end in TestParallelHarness

- .github/workflows/dockerimage-clang-3.9-ubuntu-mpich.yml
- .github/workflows/dockerimage-clang-5.0-ubuntu-mpich.yml
- .github/workflows/dockerimage-clang-8-alpine-mpich.yml
- .github/workflows/dockerimage-gcc-5-ubuntu-mpich.yml
- .github/workflows/dockerimage-gcc-6-ubuntu-mpich.yml
- .github/workflows/dockerimage-gcc-7-ubuntu-mpich.yml
- .github/workflows/dockerimage-gcc-8-ubuntu-mpich.yml
- .github/workflows/dockerimage-intel-18-ubuntu-mpich.yml
- ci/azure/azure-intel-18-ubuntu-mpich-extended.yml
- ci/azure/azure-nvidia-10-ubuntu-mpich-extended.yml
- ci/azure/azure-nvidia-11-ubuntu-mpich-extended.yml
- ci/build_cpp.sh
- cmake-modules/CheckLinkerFlag.cmake
- cmake/define_build_types.cmake
- cmake/set_linker_flags.cmake
- cmake_config.h.in
- docker-compose.yml
- src/CMakeLists.txt
- src/vt/collective/startup.h
- src/vt/configs/features/features_defines.h
- src/vt/messaging/irecv_holder.h
- tests/unit/runtime/test_initialization_with_args.cc
> 1197: prepare beta-10.4 release

- .github/workflows/macosx-clang-mpich.yml
> 1207 Fix Mac CI

- ci/build_cpp.sh
Fixes #1204
m.css has an assertion that limits the number of serialized children
and results used to build search strings by organizing them in a trie.
Commit 3fb8439 in VT introduced a new `serialize` method for
`LBManager`, which caused the number of children to exceed the amount
of storage allocated (4 bits or 16 children) due to the number of
related `serialize` methods. This commit updates VT to use the latest
version of m.css and removes the assertion during trie building for
search strings. This might cause strange behavior in searching, but
won't affect the rest of the documentation generation. A bug has been
submitted so we can hopefully remove this once they fix the bug:
https://github.com/mosra/m.css/issues/190
> 1204 Documentation building: use latest version and remove assertion from m.css

- src/vt/messaging/active.cc
> #1211: Fix warning about missing default ctor for member SendInfo

- docs/md/collection.md
- src/vt/configs/arguments/app_config.h
- src/vt/configs/arguments/args.cc
- src/vt/vrt/collection/manager.impl.h
- tests/unit/collection/test_lb.extended.cc
> #1217: Check for zero objects on a MPI rank/node case after LB runs

- ci/docker/ubuntu-18.04-clang-cpp.dockerfile
- ci/docker/ubuntu-20.04-clang-cpp.dockerfile
> 1233: clang builds fail to compile with OpenMP

- src/vt/messaging/active.cc
- src/vt/messaging/active.h
- src/vt/messaging/active.impl.h
- src/vt/messaging/async_op.cc
- src/vt/messaging/async_op.h
- src/vt/messaging/async_op_cuda.h
- src/vt/messaging/async_op_wrapper.h
- src/vt/messaging/request_holder.h
- tests/unit/active/test_async_op.cc
> 1237 Implement AsyncOp for general polling epoch tasks

- src/CMakeLists.txt
- src/vt/vrt/collection/migrate/migrate_handlers.impl.h
- src/vt/vrt/collection/migrate/migrate_msg.h
- src/vt/vrt/collection/types/migratable.h
- src/vt/vrt/collection/types/storage/storable.cc
- src/vt/vrt/collection/types/storage/storable.h
- src/vt/vrt/collection/types/storage/storable.impl.h
- src/vt/vrt/collection/types/storage/store_elm.h
- src/vt/vrt/collection/types/storage/store_elm.impl.h
- tests/unit/collection/test_invoke.cc
- tests/unit/collection/test_storage.cc
Fixes #1232
Implement a general mechanism to store data with a collection element. Implemented with a key/value store that detects whether the value needs serialization or not. The string-based key could add some overhead, but I think it's fine for the use cases we have.
> 1232 Implement Storable collection trait in support of CUDA streams

- src/vt/vrt/collection/balance/node_stats.cc
Output phase and subphase timings in stats files using scientific notation.
Closes #1249
> #1249: collection: output object loads in scientific notation

- CMakeLists.txt
- cmake/define_build_types.cmake
- src/CMakeLists.txt
Fixes #1256 
With this fix, it's no longer required to add -Dvt_trace_only
> 1256:  Create vt_trace_only option before creating trace-only CMake target

- docs/md/trace-only.md
> 1270: Rename vt-trace markdown introduction section, so it doesn't collide with vt.md

- src/vt/collective/collective_scope.cc
Switched `runScheduler` to `runSchedulerWhile` to make sure that the between schedulers event in the trace is closed, otherwise it asserts in debug builds.
Fixes #1273
> 1273: Fix runScheduler call in waitCollective

- src/vt/trace/trace.cc
When we added indirection to the registry, some prints never got updated.  This PR does that and moves the print to before the assert in `endProcessing`.
Fixes #1284
> 1284: Improve debug print in trace

- src/vt/configs/arguments/app_config.h
- src/vt/messaging/active.h
- src/vt/messaging/message/smart_ptr.h
- src/vt/pipe/callback/cb_union/cb_raw.h
- src/vt/pipe/signal/signal.h
- src/vt/rdma/state/rdma_state.h
- src/vt/rdmahandle/base_handle.h
- src/vt/rdmahandle/handle_key.h
- src/vt/rdmahandle/manager.h
- src/vt/termination/graph/epoch_graph.h
- src/vt/termination/interval/integral_set.h
- src/vt/trace/trace.h
- src/vt/vrt/collection/balance/elm_stats.impl.h
- src/vt/vrt/collection/messages/user.impl.h
- tests/unit/termination/test_term_dep_send_chain.cc
> 1258: add missing fields in 'serialize' methods

- examples/collection/migrate_collection.cc
- src/vt/vrt/collection/migrate/migrate_msg.h
> 1266: Use checkpoint::reconstructPointedToObjectIfNeeded for reconstructing migrated collection element

- src/vt/vrt/collection/balance/baselb/baselb.cc
- src/vt/vrt/collection/balance/lb_invoke/invoke.cc
- src/vt/vrt/collection/balance/proc_stats.cc
Call `startIterCleanup` where it will happen on every phase, not just ones where LB happens, so that stats output will consistently contain permanent IDs.
Fixes #1277
> 1277: Stats output mixes perm and temp IDs

- src/vt/vrt/collection/manager.impl.h
> 1292: Remove dead code in migrateIn function

- .github/workflows/graph-build-times.yml
- README.md
Fixes #1216 
What this workflow does:
- generate the graph of last 50 builds of pushdockerimage.yml workflow
- push the file of generated graph to our wiki repo
For now I've edited the [Build Requirements](https://github.com/DARMA-tasking/vt/wiki/Build-Requirements) page to use this graph.
> 1216: Add Github workflow that creates graph of VT build times and pushes it to wiki page

- CMakeLists.txt
- cmake/load_local_packages.cmake
Updated build system so that vt finds checkpoint and detector when dropped into the lib subdirectory, as it already does on develop.
Fixes #1274
> 1274: Release build system does not find deps in lib

- ci/azure/azure-clang-3.9-ubuntu-mpich.yml
- ci/azure/azure-clang-5.0-ubuntu-mpich.yml
- ci/azure/azure-clang-8-alpine-mpich.yml
- ci/azure/azure-gcc-10-ubuntu-openmpi.yml
- ci/azure/azure-gcc-5-ubuntu-mpich.yml
- ci/azure/azure-gcc-6-ubuntu-mpich.yml
- ci/azure/azure-gcc-7-ubuntu-mpich.yml
- ci/azure/azure-gcc-8-ubuntu-mpich.yml
- ci/azure/azure-gcc-9-ubuntu-mpich.yml
- ci/azure/azure-intel-18-ubuntu-mpich-extended.yml
- ci/azure/azure-intel-18-ubuntu-mpich.yml
- ci/azure/azure-intel-19-ubuntu-mpich.yml
- ci/azure/azure-nvidia-10-ubuntu-mpich-extended.yml
- ci/azure/azure-nvidia-10-ubuntu-mpich.yml
- ci/azure/azure-nvidia-11-ubuntu-mpich-extended.yml
- ci/azure/azure-nvidia-11-ubuntu-mpich.yml
- docker-compose.yml
- scripts/azure-workflow-template.yml
- scripts/workflows-azure.ini
- tests/knowns_leaks.supp
> 1317:  Memory leak exposed by address sanitizer in insertable_collection example

- docs/md/scheduler.md
- src/vt/group/global/group_default.cc
- src/vt/runtime/runtime.cc
- src/vt/runtime/runtime.h
- src/vt/scheduler/scheduler.cc
- src/vt/scheduler/scheduler.h
- src/vt/standalone/vt_main.h
- tests/perf/comm_cost_curve.cc
- tests/perf/memory_checker.cc
- tests/perf/ping_pong.cc
- tests/unit/active/test_active_bcast_put.cc
- tests/unit/active/test_active_send.cc
- tests/unit/active/test_active_send_put.cc
- tests/unit/active/test_pending_send.cc
- tests/unit/lb/test_lb_stats_reader.cc
- tests/unit/location/test_location.cc
- tests/unit/pipe/test_signal_cleanup.cc
- tests/unit/rdma/test_rdma_handle.h
- tests/unit/scheduler/test_scheduler_loop.cc
- tests/unit/scheduler/test_scheduler_priorities.extended.cc
- tests/unit/scheduler/test_scheduler_progress.extended.cc
- tests/unit/termination/test_term_cleanup.cc
- tests/unit/termination/test_termination_action_common.impl.h
- tests/unit/test_parallel_harness.h
- tests/unit/trace/test_trace_spec_reader.cc
- tutorial/tutorial_main.h
Fixes #1272 
For the most part I've changed the uses of `while() runScheduler()` to `theSched()->runSchedulerWhile()`. The exceptions were:
https://github.com/DARMA-tasking/vt/blob/4a0f2cd17d11fc2099e93bbe850acf17f02eec3e/tests/perf/memory_checker.cc#L75-L86
https://github.com/DARMA-tasking/vt/blob/4a0f2cd17d11fc2099e93bbe850acf17f02eec3e/tests/unit/scheduler/test_scheduler_loop.cc#L100-L105
</br>
Since `runScheduler` was just a wrapper for `theSched()->scheduler()` and it's meant to be used only by our internal code, I think it's better to remove `runScheduler` altogether and use  `theSched()->scheduler()` instead.
> 1272: Update the usage of scheduler in code

- src/vt/vrt/collection/balance/lb_invoke/invoke.cc
Unless we're running LB every phase, skip running LB on phase 0, which is a warm-up/app initialization phase, unless an LB spec file is used.  Now LB at intervals happens on `phase % interval == 1`.  I made this PR directly on the release branch because we already have a very similar change on develop.
Closes #1296
> 1296: Avoid running LB on warm-up phase

- src/vt/vrt/collection/balance/gossiplb/gossip_msg.h
- src/vt/vrt/collection/balance/gossiplb/gossiplb.cc
- src/vt/vrt/collection/balance/gossiplb/gossiplb.h
**This PR is the release branch-based equivalent of #1348. Please post review comments on #1348.**
Includes many bug fixes and improvements to GossipLB.  The following LB args were added:
- `trials` (default `3`): how many times to repeat the requested number of iterations, hoping to find a better imbalance; helps if it’s easy to get stuck in a local minimum
- `deterministic` (default false): for debugging purposes, make the migration decision deterministic assuming deterministic loads (for testing on deterministic loads, consider using the driver in development under #1265)
- `inform` (default SyncInform): choice of gossiping approach
- SyncInform (`0`): synchronous propagates after all recvs for a round, but has sync cost (matches LBAF approach)
- AsyncInform (`1`): asynchronous …
> 1279 gossiplb inform and decide have bugs - release branch

- src/vt/vrt/collection/balance/gossiplb/gossip_msg.h
- src/vt/vrt/collection/balance/gossiplb/gossiplb.cc
- src/vt/vrt/collection/balance/gossiplb/gossiplb.h
Includes many bug fixes and improvements to GossipLB.  The following LB args were added:
- `trials` (default `3`): how many times to repeat the requested number of iterations, hoping to find a better imbalance; helps if it’s easy to get stuck in a local minimum
- `deterministic` (default false): for debugging purposes, make the migration decision deterministic assuming deterministic loads (for testing on deterministic loads, consider using the driver in development under #1265)
- `inform` (default SyncInform): choice of gossiping approach
- SyncInform (`0`): synchronous propagates after all recvs for a round, but has sync cost (matches LBAF approach)
- AsyncInform (`1`): asynchronous propagates after the first recv for a round, but avoids sync cost
- `ordering` (default Marginal): order …
> 1279 gossiplb inform and decide have bugs

- src/vt/vrt/collection/balance/lb_invoke/lb_manager.cc
Check for a failed attempt to match the LB name in `decideLBToRun` instead of defaulting to `NoLB`.
Fixes #1366.
> 1366 LB strategy name can skip validation

- src/vt/configs/debug/debug_print.h
- src/vt/group/collective/group_info_collective.cc
- tests/unit/group/test_group.extended.cc
- tests/unit/termination/test_term_dep_send_chain.cc
When a collective registration is delayed on one node and it starts sending messages before the continuations are registered, the continuation runs but doesn't have the proper state to make progress.
Solution:
Move `makeCollectiveContinuation` call after continuation registrations.
This must be *after* all the other continuation registrations because it triggers buffered work that is waiting on the meta-continuation to be registered which checks for message counts and then dispatches to the secondary continuation.
A few more details: The call`makeCollectiveContinuation(group)`  takes the new `group` ID that is mid-construction as an argument and creates the "meta-continuation" for it, which basically says that the message dispatchers are ready for that group so messages that are held back …
> 1006: GroupCollective setup races with continuation registration code

- src/vt/vrt/collection/balance/baselb/baselb.cc
- src/vt/vrt/collection/balance/baselb/baselb.h
- src/vt/vrt/collection/balance/gossiplb/gossiplb.cc
- src/vt/vrt/collection/balance/gossiplb/gossiplb.h
- tests/unit/lb/test_gossiplb.nompi.cc
This renames the `Marginal` object ordering to `FewestMigrations` and adds @PhilMiller's `SmallObjects` ordering and the more naive `LargestObjects` ordering.  Tests for all three, along with ordering by element ID, are included.
Closes #1369
> 1369 implement additional gossiplb ordering

- tests/unit/collection/test_lb.extended.cc
The GossipLB load balancer was running in a very heavy-weight configuration in `TestLoadBalancers`, causing it to time out when oversubscribed in #1297.  I have made it more lightweight by tweaking the test.  It's still more expensive than the other load balancers and may need performance tuning.  #1376 will eventually change the default configuration to be more lightweight at small scale.
Fixes #1375.
> 1375 TestLoadBalancer tests time out with GossipLB

- src/vt/scheduler/scheduler.h
- src/vt/scheduler/scheduler.impl.h
- tests/unit/scheduler/test_high_level_calls.cc
> 1383: Add variants of runInEpoch* that take a string label as the first argument 

- src/vt/vrt/collection/balance/lb_invoke/lb_manager.cc
Release 1.0.1 skips LB on the first phase when the interval is 1 but develop does not. Update develop to match the 1.0.1 release.
Closes #1372.
> 1372 Still skip LB on first phase when interval is 1

- src/vt/vrt/collection/balance/gossiplb/gossiplb.cc
- src/vt/vrt/collection/balance/gossiplb/gossiplb.h
Changed the fanout type from uint8_t to uint16_t so that fanouts of 1 less than the number of processors can be used for "full information" with GossipLB.
Fixes #1387.
> 1387 GossipLB fanout type is too small

- src/vt/termination/epoch_tags.cc
- src/vt/termination/epoch_tags.h
- src/vt/termination/termination.cc
- src/vt/termination/termination.h
- src/vt/vrt/collection/manager.impl.h
- tests/unit/termination/test_term_cleanup.cc
- tests/unit/termination/test_termination_action_nested_collect.cc
- tests/unit/termination/test_termination_action_nested_rooted.cc
> 1079: Rewrote sucessor to parent epoch in all associated files

- ci/azure/azure-clang-10-ubuntu-mpich.yml
- ci/azure/azure-clang-3.9-ubuntu-mpich.yml
- ci/azure/azure-clang-5.0-ubuntu-mpich.yml
- ci/azure/azure-clang-8-alpine-mpich.yml
- ci/azure/azure-clang-9-ubuntu-mpich.yml
- ci/azure/azure-gcc-10-ubuntu-openmpi.yml
- ci/azure/azure-gcc-5-ubuntu-mpich.yml
- ci/azure/azure-gcc-6-ubuntu-mpich.yml
- ci/azure/azure-gcc-7-ubuntu-mpich.yml
- ci/azure/azure-gcc-8-ubuntu-mpich.yml
- ci/azure/azure-gcc-9-ubuntu-mpich.yml
- ci/azure/azure-intel-18-ubuntu-mpich-extended.yml
- ci/azure/azure-intel-18-ubuntu-mpich.yml
- ci/azure/azure-intel-19-ubuntu-mpich.yml
- ci/azure/azure-nvidia-10-ubuntu-mpich-extended.yml
- ci/azure/azure-nvidia-10-ubuntu-mpich.yml
- ci/azure/azure-nvidia-11-ubuntu-mpich-extended.yml
- ci/azure/azure-nvidia-11-ubuntu-mpich.yml
- scripts/azure-workflow-template.yml
- scripts/report_logs_in_comment.sh
Fixes #1357 
So the problem is that if for any reason the build fails without generating logs (from compilation and tests) the script gets empty reports and thinks that it means that everything went super well.
To fix this I pass the pipeline's status to the script, so if the status is not `Succeeded` or `SucceededWithIssues` and the compilation and tests reports are empty then it means that something really bad happened.
>  #1357 fix build errors reporting 

- tests/unit/sequencer/test_sequencer_extensive.extended.cc
- tests/unit/termination/test_term_dep_send_chain.cc
Fixes #1427 
Disable (skip) the tests temporarily, so we can merge our pending PRs.
> 1427: tests: Skip tests that are timing out on Azure

- src/vt/vrt/collection/balance/proc_stats.cc
Fixes #1128 on the release branch. This is a replacement for #1141, which targeted develop and applies to a different source file.
> 1128 stats files will contain tempids on release

- examples/collection/transpose.cc
- examples/hello_world/hello_world_functor.cc
- src/vt/messaging/active.h
- src/vt/messaging/active.impl.h
- src/vt/utils/static_checks/functor.h
- tutorial/tutorial_1b.h
> 1260: Fix active messaging functor inference using the FunctorExtractor

- src/vt/vrt/collection/balance/gossiplb/gossiplb.cc
- src/vt/vrt/collection/balance/gossiplb/gossiplb.h
> 1410 GossipLB: Select candidate migrant object, and then exclude ineligible recipient nodes

- src/vt/group/global/group_default.cc
- src/vt/group/global/group_default.h
- src/vt/group/group_manager.cc
- src/vt/group/group_manager.h
- src/vt/group/group_manager_active_attorney.cc
- src/vt/group/group_manager_active_attorney.h
- src/vt/messaging/active.cc
- src/vt/messaging/active.h
- src/vt/messaging/active.impl.h
- src/vt/messaging/message/smart_ptr.h
- src/vt/messaging/pending_send.cc
- src/vt/messaging/pending_send.h
- src/vt/serialization/messaging/serialized_messenger.impl.h
- src/vt/vrt/collection/manager.impl.h
- src/vt/vrt/context/context_vrtmanager.impl.h
> 1344 Avoid explicit message size in send() parameters by storing it on MsgSharedPtr

- src/vt/context/runnable_context/td.cc
- src/vt/context/runnable_context/td.h
- tests/unit/active/test_async_op_threads.cc
> 1507 context td

- src/vt/vrt/collection/manager.h
- src/vt/vrt/collection/manager.impl.h
- tests/unit/collection/test_checkpoint.extended.cc
> 1490 Write new collection restore from file in place

- src/vt/messaging/async_op.cc
- src/vt/termination/termination.cc
- src/vt/termination/termination.h
> #1480: Treat pending asynchronous operations like message in flight to prevent TD hang detection false positives

- src/CMakeLists.txt
> #1524: cmake: fix typo in export name

- src/vt/termination/termination.cc
> 1531: Add label to termination hang prints

- src/vt/vrt/collection/balance/greedylb/greedylb.cc
- src/vt/vrt/collection/balance/greedylb/greedylb.h
- src/vt/vrt/collection/balance/greedylb/greedylb_msgs.h
- tests/unit/collection/test_lb.extended.cc
Fixes #1395
- I've started by trying to identify where the bug is, and it seems anecdotally to be in the scatter.
- I determined this by implementing alternative strategies to the scatter (pt2pt send, and broadcast), which both seem to "fix" the problem. After 1000 runs it doesn't occur with both the send and broadcast, whereas before it always triggered with that many runs when scatter is enabled.
- The data indicates some bad data that occasionally shows up when scatter is enabled. However, even when it fails, address sanitizer is clean, so it's not memory corruption/overwriting
```
vt: [1] (t) lb: migrateObjectTo, obj_id=25770721283, home=-24827, from=1, to=25687, found=false
vt: [1] (t) lb: transferMigrations: obj_id=(25770721283,-24827,1), to_node=25687
```
See how the home is …
> 1395 Fix GreedyLB Bug

- src/CMakeLists.txt
> #1536: cmake: remove checkpoint/detector export from VT

- src/vt/trace/trace_common.h
`trace_common.h` was missing the include for `size_t`. It seems like on the compilers we test `size_t` was probably included by transitive includes, but this is not the case on more recent versions of gcc (tested on 11.1.0) and thus fails.
Closes #1546
> #1546: compile error with gcc11

- ci/azure/azure-clang-10-alpine-mpich.yml
- ci/azure/azure-clang-10-ubuntu-mpich.yml
- ci/azure/azure-clang-3.9-ubuntu-mpich.yml
- ci/azure/azure-clang-5.0-ubuntu-mpich.yml
- ci/azure/azure-clang-9-ubuntu-mpich.yml
- ci/azure/azure-gcc-10-ubuntu-openmpi.yml
- ci/azure/azure-gcc-5-ubuntu-mpich.yml
- ci/azure/azure-gcc-6-ubuntu-mpich.yml
- ci/azure/azure-gcc-7-ubuntu-mpich.yml
- ci/azure/azure-gcc-8-ubuntu-mpich.yml
- ci/azure/azure-gcc-9-ubuntu-mpich.yml
- ci/azure/azure-intel-18-ubuntu-mpich-extended.yml
- ci/azure/azure-intel-18-ubuntu-mpich.yml
- ci/azure/azure-intel-19-ubuntu-mpich.yml
- ci/azure/azure-nvidia-10-ubuntu-mpich-extended.yml
- ci/azure/azure-nvidia-10-ubuntu-mpich.yml
- ci/azure/azure-nvidia-11-ubuntu-mpich-extended.yml
- ci/azure/azure-nvidia-11-ubuntu-mpich.yml
- scripts/workflow-azure-template.yml
Fixes #1523 
* `continueOnError: true` makes a given task continue to next one even if there was an error. Result of failed task is `SucceededWithIssues`
* `condition: in(variables['Agent.JobStatus'], 'Succeeded', 'SucceededWithIssues')` makes a given task runnable if previus was succedded or failed, but was marked as `continueOnError`
> #1523 don't fail job on Azure infrastructure failure

- src/vt/messaging/async_op_cuda.h
> #1594: Don't try to print cudaEvent_t, since it's an incomplete type as declared by CUDA headers

- ci/build_cpp.sh
- src/vt/trace/trace_lite.cc
Fixes #1586 
----
`TraceLite` ctor tried to read from config pointer, which wasn't initialized yet.
> 1586 fix vt sample project segfault

- src/vt/configs/arguments/args.cc
> #1607 Fix UBSAN error 'applying non-zero offset ... to null pointer'

- .clang-format
Fixes #1592 
----
About the preprocessor directives indention, what style do we prefer?
(paragraph `IndentPPDirectives` at https://clang.llvm.org/docs/ClangFormatStyleOptions.html)
`None`:
```cpp
#if FOO
#if BAR
#include <foo>
#endif
#endif
```
`AfterHash`:
```cpp
#if FOO
#endif
```
`BeforeHash`:
```cpp
#if FOO
#if BAR
#include <foo>
#endif
#endif
```
Currently we have `BeforeHash`.
> #1592 Update clang-format configuration

- lib/CLI/CLI/CLI11.hpp
- src/vt/configs/arguments/args.h
Fixes #1604 
----
I didn't upgrade CLI11 to the newest version, API changed a bit. If we want to do so, let's open another issue for that. Also script generating single header file was changed, and I opened issue in CLI11 repo reporting problem with support for custom namespace - before upgrading we want it to be fixed
https://github.com/CLIUtils/CLI11/issues/680
> #1604 put CLI11 in vt namespace

- cmake/load_bundled_libraries.cmake
- lib/fmt/include/fmt/core.h
- src/vt/elm/elm_id.h
- src/vt/epoch/epoch_type.h
Fixes #1605 
---
`fmt` has macros `FMT_BEGIN_NAMESPACE` and `FMT_END_NAMESPACE`, but unfortunately, internally it explicitly uses full namespace (in core.h):
```cpp
namespace detail {
void to_string_view(...);
using fmt::v7::to_string_view;
...
```
To use it, we would have to hardcode our namespace anyway.
To solve this I extracted this "inner" namespace into an additional macro, so it could be simply defined in cmake.
---
I opened an issue in fmt repo regarding this problem
fmtlib/fmt#2642
---
I copied their fix into our `fmt/core.h` and define `FMT_BEGIN_NAMESPACE` and `FMT_END_NAMESPACE`.
> #1605 fmt custom namespace

- src/vt/vrt/collection/manager.impl.h
> #1643: Fix EMPIRE compilation error - method is untested within vt

- cmake-modules/SetCXXCompilerFlags.cmake
- cmake/load_bundled_libraries.cmake
- tests/lsan.supp
Fixes #1557 
---
BTW, I still get tons of reports like this one:
```
1: Indirect leak of 15 byte(s) in 1 object(s) allocated from:
1:     #0 0x7f0b3a5539f7 in __interceptor_strdup ../../../../src/libsanitizer/asan/asan_interceptors.cpp:454
1:     #1 0x7f0b34e5c171  (<unknown module>)
```
Did anyone have similar problem with unknown module, and maybe found a solution?
> #1557 asan openmp suppression

- src/vt/scheduler/scheduler.cc
- src/vt/scheduler/scheduler.h
Fixes #1443 
---
In the end, I decided to take a "RAII" approach. I think it will be easier to (if ever necessary) add new functionalities for loop start and loop end this way, than remembering to also change try-catch block.
> #1443 Make the scheduler loop exception-safe

- tests/unit/collection/test_lb.extended.cc
> #1654: tests: split up LB parameterization to reduce time per test instance

- .clang-format
- src/vt/configs/debug/debug_print.cc
- src/vt/configs/debug/debug_print.h
- src/vt/runtime/runtime_get.cc
- tests/unit/runtime/test_temp_enabling_debug_prints.nompi.cc
> #1636 add API for temporarily enabling/disabling debug prints

- ci/deps/libunwind.sh
- ci/docker/alpine-cpp.dockerfile
- ci/docker/ubuntu-18.04-clang-cpp.dockerfile
- ci/docker/ubuntu-18.04-gnu-cpp.dockerfile
- ci/docker/ubuntu-18.04-intel-cpp.dockerfile
- ci/docker/ubuntu-18.04-intel-oneapi-cpp.dockerfile
- ci/docker/ubuntu-18.04-nvidia-cpp.dockerfile
- ci/docker/ubuntu-20.04-clang-cpp.dockerfile
- ci/docker/ubuntu-20.04-gnu-cpp.dockerfile
- ci/docker/ubuntu-20.04-gnu-openmpi-cpp.dockerfile
- cmake/link_vt.cmake
- src/vt/configs/error/stack_out.cc
- src/vt/configs/error/stack_out.h
- src/vt/runtime/runtime.cc
- tests/unit/configs/test_stack_dumping.cc
fixes #1495
Fixes the stack dumping issues with Alpine build by replacing `libexecinfo` with `libunwind`.
Does a minor cleanup of our backtrace-generating code as well.
---
~cc52339 is the simplest workaround to the failing test - it just disables stack printing. I will try to come up with an actual fix.~
~Confirmed that it works with:~
```
ctest --output-on-failure --repeat-until-fail 100 -R TestMpiAccessGuardDeathTest.test_mpi_access_prevented_proc_2
```
~(unfixed version crashes every couple of runs).~
> 1495: fix Alpine build

- src/vt/vrt/collection/balance/baselb/baselb.cc
> #1680: lb: only add to migration if its actually a migration

- docs/md/tutorial.md
- examples/hello_world/objgroup.cc
- src/vt/collective/collective_ops.cc
- src/vt/collective/collective_ops.h
- src/vt/collective/startup.cc
- src/vt/collective/startup.h
- src/vt/configs/arguments/args.cc
- src/vt/configs/arguments/args.h
- src/vt/runtime/runtime.cc
- src/vt/runtime/runtime.h
- tests/unit/runtime/test_initialization.cc
> #1550 allow passing appconfig to vt during init

- src/vt/messaging/collection_chain_set.h
- src/vt/messaging/collection_chain_set.impl.h
- src/vt/rdmahandle/manager.collection.impl.h
- src/vt/vrt/collection/holders/holder.h
- src/vt/vrt/collection/holders/holder.impl.h
- src/vt/vrt/collection/listener/listen_events.h
- src/vt/vrt/collection/manager.impl.h
- tests/unit/termination/test_collection_chainset_tracking.cc
- tests/unit/termination/test_term_dep_send_chain.cc
> 1660 Associate proxy with chain set to track automatically

- src/vt/pmpi/generate_mpi_wrappers.pl
- tests/unit/runtime/test_mpi_access_guards.cc
> 1533: Fix typo in MPI access guard error message

- src/vt/vrt/collection/manager.impl.h
This PR does not include a test, but it has been tested in a DARMA-based application. #1709 will provide appropriate testing once completed.
Fixes #1708
> 1708 Subdirectory creation for checkpointing fails on empty rank

- .clang-format
- scripts/post-commit
- Update .clang-format to match Clang 13 syntax.
- Add post-commit hook to format modified code
- requires `git clang-format` plugin
- post-commit works better for me, but this could be easily adapted to pre-commit as well
fixes #1699
> 1699: Update `.clang-format` syntax

- src/vt/configs/features/features_defines.h
> 1713: fix spurious warning in startup banner

- tests/unit/collection/test_broadcast.cc
- tests/unit/collection/test_broadcast.extended.cc
- tests/unit/collection/test_broadcast.h
- tests/unit/collection/test_collection_construct_common.h
- tests/unit/collection/test_construct.cc
- tests/unit/collection/test_construct_no_idx.extended.cc
- tests/unit/collection/test_send.cc
- tests/unit/collection/test_send.extended.cc
- tests/unit/collection/test_send.h
- tests/unit/rdma/test_rdma_handle.cc
- tests/unit/rdma/test_rdma_handle.extended.cc
- tests/unit/rdma/test_rdma_handle.h
> 1736: Fix tests defined in headers

- lib/EngFormat-Cpp/src/eng_format.cpp
> #1749 use `std::numeric_limits::epsilon` instead of `DBL_EPSILON`

- src/vt/vrt/collection/holders/collection_context_holder.h
- src/vt/vrt/collection/manager.h
- src/vt/vrt/collection/manager.impl.h
> #1747: change const pointer to pointer to const IndexT

- src/vt/messaging/active.cc
- src/vt/objgroup/manager.cc
- src/vt/vrt/collection/balance/col_lb_data.impl.h
- src/vt/vrt/collection/balance/lb_data_holder.cc
- src/vt/vrt/collection/balance/lb_data_holder.h
- src/vt/vrt/collection/balance/node_lb_data.cc
- src/vt/vrt/collection/balance/node_lb_data.h
- src/vt/vrt/collection/types/storage/storable.cc
- src/vt/vrt/collection/types/storage/storable.h
- src/vt/vrt/collection/types/storage/storable.impl.h
- src/vt/vrt/collection/types/storage/store_elm.h
- tests/unit/collection/test_lb.extended.cc
This PR adds the ability to dump items stored in collection elements as user-defined data in LB data json files. I also added a commit that removes some stale lines of code from an existing unit test.
Closes #1723
> 1723 Include user-defined fields in json LB data files

- src/vt/vrt/collection/balance/lb_invoke/lb_manager.h
In support of LB data replay.
Closes #1756.
> 1756 Allow computing LB statistics from outside LBManager

- src/vt/vrt/collection/balance/baselb/baselb.h
In support of LB data replay.
Closes #1755
> 1755 Allow LB itself to call normalizeReassignments

- src/vt/vrt/collection/balance/lb_invoke/lb_manager.cc
- src/vt/vrt/collection/balance/lb_invoke/lb_manager.h
In support of LB data replay.
Closes #1757
> 1757 Allow destroying an LB from outside the LBManager

- src/vt/vrt/collection/balance/model/raw_data.cc
Partly in support of LB data replay.
Fixes #1761
> 1761 workaround for mismatched subphase counts

- src/vt/messaging/active.cc
- src/vt/termination/dijkstra-scholten/ds.cc
> 1788 migrate collection test failure due to ds epochs

- ci/docker/ubuntu-20.04-gnu-openmpi-cpp.dockerfile
- cmake/link_vt.cmake
Fixes #1786. Follow-up to issue #1691.
> #1786: condition link flag on library's presence

- src/vt/group/region/group_list.cc
- src/vt/group/region/group_list.h
> 1782: fix dangling pointer warning

- src/vt/vrt/collection/balance/temperedlb/temperedlb.cc
As previously coded, `TemperedLB` would never skip LB due to low imbalance. Instead of changing the value, which is consistent with other LBs, I fixed the formula used for evaluating.
Fixes #1460
> 1460 fix bug in temperedlb tolerance

- ci/build_cpp.sh
The `.` must come before the `-j N`.
Fixes #1818
> 1818 Fix argument reversal in build_cpp script

- cmake/turn_on_warnings.cmake
fixes #1799 
- `check_cxx_compiler_flag` doesn't seem to work correctly for this flag (and compilers).
- I have verified that flags are applied correctly for `icpc 2021.6.0`, so I assume that only older versions require this additional `if`.
- AFAIK no [Intel-specific flag](https://www.intel.com/content/www/us/en/develop/documentation/cpp-compiler-developer-guide-and-reference/top/compiler-reference/compiler-options/alphabetical-list-of-compiler-options.html) is available.
@lifflander I don't have access to Intel 18/19, so someone has to verify this before merging.
> 1799: do not apply `-ftemplate-backtrace-limit` for older `icpc` versions

- .github/workflows/comment-on-pr.yml
- scripts/report_logs_in_comment.sh
> #1803 Concatenate compilation reports into one PR comment

- src/vt/utils/bits/bits_packer.h
- src/vt/utils/bits/bits_packer.impl.h
> #1839: use unsigned types for left shifts in BitPacker

- src/vt/topos/index/dense/dense_array.h
- src/vt/topos/index/index.h
- src/vt/topos/mapping/dense/dense.h
- src/vt/topos/mapping/dense/dense.impl.h
- src/vt/vrt/collection/defaults/default_map.h
- tests/unit/collection/test_collection_construct_common.h
- tests/unit/collection/test_construct.cc
- tests/unit/collection/test_construct_no_idx.extended.cc
> 1544: Implement default_map for indices with more than 3 dimensions

- CTestConfiguration.ini
This should result in CMake builds and test results reporting to the VT project.
Closes #1853
> 1853 This adds the CTestConfiguration.ini file from the VT project

- cmake/configure_options.cmake
> #1563: cmake: enable MPI guards by default regardless of build

- ci/ctest_job_script.cmake
Don't build or test if configure fails. Don't test if build fails. I also removed the command that clears out the directory because it always fails (for safety, the command only functions correctly if finds a `CMakeLists.txt` file) due to always starting from scratch.
Closes #1869
> 1869 Avoid testing when gitlab CI build fails

- src/vt/vrt/collection/balance/lb_invoke/lb_manager.cc
- src/vt/vrt/collection/balance/lb_invoke/lb_manager.h
Open the LB statistics json file on first use so that apps have time to programmatically change the options.
Fixes #1881
> 1881 LB statistics json file opened too early

- tests/unit/collection/test_checkpoint.extended.cc
- tests/unit/collection/test_lb.extended.cc
- tests/unit/runtime/test_initialization.cc
- tests/unit/test_helpers.h
- tests/unit/test_parallel_harness.h
- tests/unit/trace/test_trace_spec_reader.cc
This PR attempts to stop using the same disk files from multiple unit tests, including runs with different numbers of MPI ranks, so that multiple tests can be run concurrently (as happens in Gitlab CI testing) without file system conflicts. ~~This PR does not yet handle parameterizations or filenames/directories used for LB data files in `addAdditionalArgs()` in `collection/test_lb.extended.cc`. Does anyone have ideas on how to tackle those?~~
Closes #1896
> 1896 Use only unique filenames in unit tests

- src/vt/configs/debug/debug_print.h
> #1908: Disable preConfig

- src/vt/context/context.h
- src/vt/messaging/active.cc
- src/vt/messaging/active.h
> 1909 Cache the MPI communicator in ActiveMessenger

- src/vt/messaging/envelope/envelope_ref.impl.h
> 1912 Use assert to optimize production path check

- src/vt/event/event.cc
- src/vt/event/event.h
- src/vt/messaging/active.cc
- src/vt/messaging/active.h
- src/vt/runtime/component/component.h
- src/vt/runtime/component/component_pack.cc
- src/vt/runtime/component/component_pack.h
- src/vt/runtime/component/progressable.h
- src/vt/runtime/runtime.h
- src/vt/scheduler/scheduler.cc
- src/vt/scheduler/scheduler.h
- src/vt/timetrigger/time_trigger_manager.cc
- src/vt/timetrigger/time_trigger_manager.h
- src/vt/timetrigger/trigger.h
- src/vt/worker/worker_group.h
- src/vt/worker/worker_group.impl.h
- src/vt/worker/worker_group_omp.cc
- src/vt/worker/worker_group_omp.h
Closes #1901. Pass the current time from the scheduler to the progress functions.
> 1901 MPI_Wtime called many times per handler invocation

- tests/unit/lb/test_lb_data_comm.cc
> #1955: Suppress spurious warning about method declared but not used

- ci/ctest_job_script.cmake
The job pool only gives build parallelism to Ninja builds under Gitlab CI. This PR gives a `-j` argument when using Unix Makefiles (that we're forced to use for one of the Gitlab CI builds for the time being).
Closes #1964
> 1964 Work around serial Gitlab CI build with unix makefiles

- src/vt/scheduler/base_unit.cc
- src/vt/scheduler/scheduler.cc
- src/vt/scheduler/scheduler.h
- src/vt/scheduler/suspended_units.cc
Closes #1943. Add vt_check_enabled statements to reduce unneeded code in the scheduler.
> 1943 scheduler check optimizations

- src/vt/termination/termination.cc
- src/vt/termination/termination.h
> #1967: TD: add enable/disable for performance tests

- src/vt/context/runnable_context/td.cc
- src/vt/messaging/active.cc
- src/vt/messaging/active.h
- src/vt/messaging/active.impl.h
- src/vt/termination/termination.cc
- src/vt/termination/termination.h
- src/vt/termination/termination.impl.h
- tests/unit/active/test_async_op_threads.cc
Closes #1941. Add EpockStack to TerminationDetector.
> 1941 move EpochStack to TerminationDetector

- src/vt/runtime/component/component_pack.cc
- src/vt/runtime/component/component_pack.h
- src/vt/runtime/component/progressable.h
- src/vt/runtime/runtime.h
- src/vt/scheduler/scheduler.cc
- src/vt/scheduler/scheduler.h
- src/vt/timetrigger/time_trigger_manager.cc
- src/vt/timetrigger/time_trigger_manager.h
> #1969: scheduler: reduce calls to get the current time

- ci/ctest_job_script.cmake
CDash will now have an `Update` column with a `Revision` sub-column header that includes the git sha. Without this, I don't think there is a way to know what was built.
Closes #1994
> 1994 Add commit sha to cdash output

- tests/unit/collection/test_collection_group.extended.cc
- tests/unit/lb/test_lb_data_comm.cc
Depends on https://github.com/DARMA-tasking/magistrate/pull/266
Fixes #1999
> #1999 Fix icpc/nvcc warnings seen in CDash

- src/vt/messaging/active.cc
- src/vt/messaging/active.impl.h
- src/vt/termination/termination.cc
- src/vt/termination/termination.impl.h
Closes #1932. 
Remove some calls to theContext() in ActiveMessenger and TerminationDetector via using a member variable or a local variable.
> 1932 reduce calls to thecontext

- tests/unit/collection/test_lb_data_retention.cc
> 2007: Skip TestLBDataRetention tests when num_ranks > num_elems

- src/vt/vrt/collection/collection_builder.impl.h
- tests/unit/collection/test_list_insert.cc
> #2001: Avoid reconstruction when pre-constructed elements are present in collection

- src/vt/context/runnable_context/collection.cc
- src/vt/context/runnable_context/collection.h
- src/vt/context/runnable_context/continuation.h
- src/vt/context/runnable_context/lb_data.cc
- src/vt/context/runnable_context/lb_data.h
- src/vt/context/runnable_context/set_context.cc
- src/vt/context/runnable_context/set_context.h
- src/vt/context/runnable_context/td.cc
- src/vt/context/runnable_context/td.h
- src/vt/context/runnable_context/trace.cc
- src/vt/context/runnable_context/trace.h
- src/vt/runnable/runnable.cc
- src/vt/runnable/runnable.h
> 2002: Runnable: Rename begin()/end() to start()/finish()

- src/vt/trace/trace_user.h
> #2019: add move constructor/assign to TraceScopedEvent and TraceScopedNote

- src/vt/serialization/sizer.h
- src/vt/topos/location/location.h
- src/vt/topos/location/location.impl.h
- src/vt/topos/location/message/msg.h
- src/vt/vrt/collection/manager.impl.h
- src/vt/vrt/context/context_vrtmanager.impl.h
- tests/unit/location/test_location_common.h
Grab the low-hanging bits from #1984 to merge now - everything I've posted here were changes that I reviewed in full and would approve there.
Fixes: #2030
> 2030: Cleanup location management code

- src/vt/runnable/make_runnable.h
- tests/perf/collection_local_send.cc
- tests/perf/collection_local_send_prealloc.cc
- tests/perf/common/test_harness.h
- tests/perf/make_runnable_micro.cc
- tests/perf/objgroup_local_send.cc
- tests/perf/ping_pong.cc
- tests/perf/ping_pong_am.cc
- tests/perf/reduce.cc
Closes #1930. Depends on changes to runnable (e.g., makeRunnable, RunnableNew) from #1899 and #1914, and possibly others.
> 1930 Add new microbenchmarks

- src/vt/topos/location/location.impl.h
> #2040 Clarify reference to static member functions in template argument to appease nvcc 11.4

- src/vt/vrt/collection/types/storage/storable.h
> #2043: Suppress nvcc's bogus implicit generation of a copy constructor for an uncopyable class

- src/vt/vrt/collection/balance/zoltanlb/zoltanlb.h
> 2048: Remove duplicated `struct CommMsg`

- .github/workflows/macosx-clang-mpich.yml
> 1920 update mac build

- .github/workflows/build-docs.yml
- .github/workflows/build-statistics.yml
- .github/workflows/check-commit-format.yml
- .github/workflows/check-include-guards.yml
- .github/workflows/check-trailing-whitespace.yml
- .github/workflows/macosx-clang-mpich.yml
- .github/workflows/pushdockerimage.yml
- .github/workflows/run-git-check.yml
- ci/azure/azure-clang-10-ubuntu-mpich.yml
- ci/azure/azure-clang-11-ubuntu-mpich.yml
- ci/azure/azure-clang-12-ubuntu-mpich.yml
- ci/azure/azure-clang-13-ubuntu-mpich.yml
- ci/azure/azure-clang-14-ubuntu-mpich.yml
- ci/azure/azure-clang-5.0-ubuntu-mpich.yml
- ci/azure/azure-clang-9-ubuntu-mpich.yml
- ci/azure/azure-clang-alpine-mpich.yml
- ci/azure/azure-gcc-10-ubuntu-openmpi.yml
- ci/azure/azure-gcc-11-ubuntu-mpich.yml
- ci/azure/azure-gcc-12-ubuntu-mpich.yml
- ci/azure/azure-gcc-7-ubuntu-mpich.yml
- ci/azure/azure-gcc-8-ubuntu-mpich.yml
- ci/azure/azure-gcc-9-ubuntu-mpich.yml
- ci/azure/azure-intel-oneapi-icpc-ubuntu-mpich.yml
- ci/azure/azure-intel-oneapi-icpx-ubuntu-mpich.yml
- ci/azure/azure-nvidia-10-ubuntu-mpich.yml
- ci/azure/azure-nvidia-11-ubuntu-mpich.yml
- scripts/workflow-azure-template.yml
- scripts/workflows-azure.ini
- update `actions/checkout` to `v3`
- update `actions/cache` as well
- remove an obsolete step from Azure workflows
fixes #2053
> 2053: update GitHub actions versions

- src/vt/pool/static_sized/memory_pool_equal.impl.h
- src/vt/runnable/runnable.cc
> 2062 Fix duplicate symbols on some Mac builds

- cmake/load_bundled_libraries.cmake
> 2066: Remove cxx standard override for bundled libraries

- src/vt/collective/collective_ops.h
- src/vt/configs/types/types_sentinels.h
- src/vt/configs/types/types_type.h
> #2071: make pre-worker-removal init call deprecated

- ci/docker/ubuntu-intel-oneapi-cpp.dockerfile
> 2068: Use specific version of intel oneapi for docker image

- src/vt/vrt/collection/balance/lb_data_restart_reader.cc
- src/vt/vrt/collection/balance/lb_data_restart_reader.h
- tests/unit/lb/test_offlinelb.cc
> 2087 fix curr node on restart reader

- src/vt/context/runnable_context/lb_data.cc
- src/vt/context/runnable_context/lb_data.h
- src/vt/context/runnable_context/trace.cc
- src/vt/context/runnable_context/trace.h
- src/vt/elm/elm_lb_data.cc
- src/vt/elm/elm_lb_data.h
- src/vt/parameterization/parameterization.h
- src/vt/rdma/state/rdma_state.cc
- src/vt/runnable/invoke.h
- src/vt/runnable/make_runnable.h
- src/vt/runnable/runnable.cc
- src/vt/runnable/runnable.h
- src/vt/scheduler/base_unit.cc
- src/vt/scheduler/scheduler.cc
- src/vt/scheduler/scheduler.h
- src/vt/trace/trace.cc
- src/vt/trace/trace.h
- tests/unit/scheduler/test_scheduler_timings.cc
Closes #1938.
~~Pass the current time from the scheduler to LB and Trace contexts.~~ 
This has been modified to allow the scheduler to hold a `current_sched_time_` and then the appropriate runnable contexts (here LB and Trace) can query their start time from the scheduler. This change was primarily the result of not wanting to force all runnable contexts to take a time (even in contexts where that is inappropriate). Still targets the issue by reducing calls to MPI_Wtime (although increased dereferencing of the `theSched()`)
> 1938 remove unneeded calls to mpi wtime in trace and lb

- ci/azure/azure-nvidia-11-2-ubuntu-mpich.yml
- ci/azure/azure-nvidia-11-ubuntu-mpich.yml
- ci/docker/ubuntu-nvidia-cpp.dockerfile
- scripts/workflows-azure.ini
> #2075: Update nvidia docker to use official image

- src/vt/runnable/runnable.h
> 2091: fix `missing return statement` warning

- tests/unit/runtime/test_preconfig.nompi.cc
> #2068: disable vtAssert test for Intel Classic

- src/vt/objgroup/proxy/proxy_objgroup.impl.h
- src/vt/objgroup/proxy/proxy_objgroup_elm.impl.h
- src/vt/vrt/collection/broadcast/broadcastable.impl.h
- src/vt/vrt/collection/send/sendable.impl.h
> #2111: Silence `nvcc` warnings

- scripts/JSON_data_files_validator.py
- src/vt/runtime/runtime.cc
- src/vt/runtime/runtime.h
- src/vt/utils/json/json_appender.h
- src/vt/vrt/collection/balance/lb_invoke/lb_manager.cc
- src/vt/vrt/collection/balance/node_lb_data.cc
- tests/unit/collection/test_lb.extended.cc
- tests/unit/lb/test_lb_data_comm.cc
- tests/unit/lb/test_offlinelb.cc
> #2098: runtime: add code to generate node IDs

- src/CMakeLists.txt
> #2119: cmake: install target for checkpoint when included in lib

- .github/workflows/comment-on-pr.yml
Fixes #2138 
Revert back change made in https://github.com/DARMA-tasking/vt/commit/baa8413712361f9bb01f1d30b9d2e3379f7ff3bf
> #2138: CI: Change concurrency to use PR number instead of branch name

- scripts/JSON_data_files_validator.py
- src/vt/vrt/collection/balance/lb_data_holder.cc
- src/vt/vrt/collection/balance/lb_data_holder.h
- src/vt/vrt/collection/balance/node_lb_data.cc
- tests/unit/collection/test_lb_data_holder.cc
> #2130: Add spec for skipped and identical phases

- src/vt/context/runnable_context/trace.cc
- src/vt/trace/trace.cc
- src/vt/trace/trace_lite.h
- tests/CMakeLists.txt
- tests/unit/trace/test_runnable_context_trace.cc
Closes #2147
I'm going to see if it is possible to add some tests, since we don't have any trace tests.
> #2147: fix incorrect order of parameters for call to beginProcessing

- CMakeLists.txt
> #2144: Fix unwanted cache export

- src/vt/utils/demangle/demangle.cc
- tests/unit/utils/test_demangler_utils.nompi.cc
> #2166: demangling: write work-around for Intel compilers

- ci/azure/azure-gcc-10-ubuntu-openmpi-spack.yml
> #2163: Fix Spack CI job issue

- src/vt/objgroup/manager.impl.h
- src/vt/runnable/invoke.h
- src/vt/vrt/collection/manager.h
- src/vt/vrt/collection/manager.impl.h
- tests/unit/runnable/test_invoke.cc
> #2140: Simplify `vt::invoke`

- src/vt/vrt/collection/types/storage/store_elm.h
> #2193: lb: stop using initializer list for json

- src/vt/vrt/collection/collection_builder.impl.h
- tests/unit/collection/test_list_insert_here.cc
> #2190: collection: fix group construction with listInsertHere

- src/vt/termination/term_action.cc
- src/vt/termination/term_action.h
- src/vt/termination/term_action.impl.h
- src/vt/termination/termination.cc
- tests/unit/termination/test_term_chaining.cc
> #2195: termination: make actions run consistently in a runnable

- docs/md/mainpage.md
> #2200: Link to documentation for other libraries

- scripts/JSON_data_files_validator.py
- src/vt/phase/phase_manager.h
- src/vt/vrt/collection/balance/lb_data_holder.cc
- src/vt/vrt/collection/balance/lb_data_holder.h
- tests/unit/collection/test_lb.extended.cc
> #2171: Implement addUserDefinedData function to PhaseManager

- src/vt/group/collective/group_info_collective.cc
- src/vt/runtime/runtime.cc
> #2125: Fix sprintf warnings

- examples/hello_world/objgroup.cc
- src/vt/group/group_manager.cc
- src/vt/group/group_manager.h
- src/vt/group/region/group_region.h
- src/vt/objgroup/proxy/proxy_objgroup.h
- src/vt/objgroup/proxy/proxy_objgroup.impl.h
- tests/unit/objgroup/test_objgroup.cc
Fixes #2094 
*******
```c++
#include "common/test_harness.h"
#include <vt/transport.h>
#include <fmt-vt/core.h>
using namespace vt;
using namespace vt::tests::perf::common;
struct MyTest : PerfTestHarness { };
struct NodeObj {
void handler(int, int b) {
}
};
VT_PERF_TEST(MyTest, test_objgroup_send) {
using namespace ::vt::group::region;
const auto num_nodes = vt::theContext()->getNumNodes();
auto proxy = vt::theObjGroup()->makeCollective<NodeObj>(
"test_objgroup_local_send");
List::ListType range;
for(NodeType n = 0; n < num_nodes - 1; ++n){
range.push_back(n);
}
if (theContext()->getNode() == 0) {
for(auto& node : range){
proxy[node].send<&NodeObj::handler>(10, 20);
}
for(auto& node : range){
proxy[node].send<&NodeObj::handler>(10, 20);
}
}
vt::theCollective()->barrier();
} …
```
> 2094: Allow ObjGroup broadcast to selected nodes

- src/vt/collective/reduce/reduce_manager.cc
- src/vt/messaging/active.h
- src/vt/messaging/active.impl.h
- src/vt/messaging/param_msg.h
- src/vt/messaging/param_msg.impl.h
- src/vt/messaging/pending_send.h
- src/vt/objgroup/proxy/proxy_objgroup.impl.h
- src/vt/objgroup/proxy/proxy_objgroup_elm.impl.h
- src/vt/pipe/callback/cb_union/cb_raw_base.h
- src/vt/vrt/collection/broadcast/broadcastable.impl.h
- src/vt/vrt/collection/messages/param_col_msg.h
- src/vt/vrt/collection/send/sendable.impl.h
- tests/unit/active/test_active_send.cc
Fixes #2212
- Adds message properties to generated/synthesized messages that are parameterized.
- I had to move the parameters going into `ParamMsg` from the constructor to a method `setParams` so I could safely modify the message is `MsgProps` are passed. Otherwise, I would have to save the `MsgProps` to apply them after the constructor finishes.
> 2212 add message properties for generated messages

- src/vt/configs/error/stack_out.h
- src/vt/utils/compress/decompressor_base.h
fixes #2225 
Stumbled upon this when working on NimbleSM :slightly_smiling_face:
> #2225: fix missing `<cstdint>` include

- ci/azure/azure-nvidia-11-2-ubuntu-mpich.yml
- scripts/workflows-azure.ini
> 2235: Bump CUDA version for CI

- src/vt/vrt/collection/balance/workload_replay.cc
- src/vt/vrt/collection/balance/workload_replay.h
- tests/unit/collection/test_workload_data_migrator.cc
- tools/workload_replay/simulate_replay.cc
> 2243 allow replay to repeat phases using modulus

- src/vt/phase/phase_manager.cc
> 2245: phase: omit print of post-lb stats when no migration

- ci/azure/azure-nvidia-12-ubuntu-mpich.yml
- scripts/workflows-azure.ini
> #2237: Update nvidia-12 build to use CUDA 12.2

- src/vt/collective/startup.h
> #2254: startup: add missing mpi header include

- src/vt/vrt/collection/balance/lb_invoke/lb_manager.cc
Closes #2258.
I used terse debug prints for *phase*, not the LB manager, so they get turned on when the post-LB statistics prints get turned on. Turning them on with the LB manager would have added a bunch of other prints as well, which is not desirable.
> #2258: lb: add timers for lb proper and migration

- src/vt/timing/timing.h
- tests/unit/timing/test_timing.nompi.cc
Closes #2256. Three sig figs isn't enough to make nice plots using the timing output.
> #2256: timing: add more significant figures

- tests/perf/common/test_harness_macros.h
> #2270: Fix ASAN error when running perf tests

- tests/perf/common/test_harness.cc
- tests/perf/common/test_harness.h
- tests/perf/common/test_harness_macros.h
Fixes #2275
--------------
<br><br>
---------------
<br><br>
---------------
> #2275: Improve `PerfTestHarness`

- tests/perf/collection_local_send.cc
- tests/perf/make_runnable_micro.cc
- tests/perf/objgroup_local_send.cc
- tests/perf/ping_pong.cc
- tests/perf/ping_pong_am.cc
- tests/perf/reduce.cc
> #2283: Cleanup performance tests

- src/vt/configs/arguments/args.cc
> #2161: Fix comment typo in `args.cc`

- tests/perf/send_cost.cc
Fixes #2249 
`BuildStats` issue - https://github.com/DARMA-tasking/build-stats/issues/31
> #2249: Add perf test for raw MPI Send/Recv and ObjGroup's Send

- docs/md/node-lb-data.md
> #2124:  Update docs on LB data file format

- cmake/link_vt.cmake
- src/vt/collective/collective_ops.cc
- src/vt/configs/error/stack_out.cc
- src/vt/runtime/runtime.cc
- src/vt/vrt/collection/balance/lb_data_restart_reader.cc
- src/vt/vrt/collection/balance/lb_data_restart_reader.h
- src/vt/vrt/collection/balance/lb_invoke/lb_manager.cc
- src/vt/vrt/collection/balance/offlinelb/offlinelb.cc
- src/vt/vrt/collection/balance/read_lb.cc
- src/vt/vrt/collection/balance/read_lb.h
- tests/unit/lb/test_lb_reader.nompi.cc
- tests/unit/lb/test_offlinelb.cc
- tests/unit/runtime/test_initialization.cc
Closes #2074 
~~Depends on #2137~~
~~Depends on #2250~~
> #2074: support sparse OfflineLB maps

- src/vt/vrt/collection/balance/lb_data_holder.cc
- tests/unit/collection/test_lb_data_holder.cc
> #2307: Fix invalid `time` format in LBDatafile

- .github/workflows/build-docs.yml
- .github/workflows/build-statistics.yml
- .github/workflows/check-commit-format.yml
- .github/workflows/check-include-guards-and-license.yml
- .github/workflows/check-trailing-whitespace.yml
- .github/workflows/macosx-clang-mpich.yml
- .github/workflows/pushdockerimage.yml
- .github/workflows/run-git-check.yml
- ci/azure/azure-clang-10-ubuntu-mpich.yml
- ci/azure/azure-clang-11-ubuntu-mpich.yml
- ci/azure/azure-clang-12-ubuntu-mpich.yml
- ci/azure/azure-clang-13-ubuntu-mpich.yml
- ci/azure/azure-clang-14-ubuntu-mpich.yml
- ci/azure/azure-clang-9-ubuntu-mpich.yml
- ci/azure/azure-clang-alpine-mpich.yml
- ci/azure/azure-gcc-10-ubuntu-openmpi.yml
- ci/azure/azure-gcc-11-ubuntu-mpich.yml
- ci/azure/azure-gcc-12-ubuntu-mpich.yml
- ci/azure/azure-gcc-8-ubuntu-mpich.yml
- ci/azure/azure-gcc-9-ubuntu-mpich.yml
- ci/azure/azure-intel-oneapi-icpc-ubuntu-mpich.yml
- ci/azure/azure-intel-oneapi-icpx-ubuntu-mpich.yml
- ci/azure/azure-nvidia-11-2-ubuntu-mpich.yml
- ci/azure/azure-nvidia-12-ubuntu-mpich.yml
- docker-compose.yml
- docs/md/building.md
- scripts/check_containers.sh
- scripts/workflow-azure-template.yml
> #2312: Update CI jobs to resolve all warnings.

- ci/build_cpp.sh
> #2308: Update `build_cpp.sh` to use `-DKokkos_ROOT`

- src/vt/objgroup/proxy/proxy_objgroup.impl.h
> #2318: Fix and issue with multicast not sending to all required nodes

- src/vt/vrt/collection/balance/lb_invoke/lb_manager.cc
- src/vt/vrt/collection/balance/lb_invoke/lb_manager.h
Reproduced with Intel `2023.2.0` and `2024.2.0`. Our Azure builds are using `2022.2.1`, so maybe we need to update them.
Explicit instantiation also solves this.
fixes #2319
> #2319: fix undefined reference to `makeLB` in collection_extended

- cmake/load_local_packages.cmake
- src/CMakeLists.txt
> #2323: Fix an issue with magistrate target when it's included as a vt's subdirectory

- CITATION.cff
- README.md
- References.bib
> #2198: initial citation file

- cmake/link_vt.cmake
- cmake/load_packages.cmake
- cmake/load_zlib_package.cmake
Fixes #2321 
---
The problem was in `load_zlib_package.cmake`:
```cmake
find_package(ZLIB REQUIRED)
if(ZLIB FOUND)
include_directories(${ZLIB_INCLUDE_DIRS})
...
```
The `zlib` includes found by CMake were in a directory that also contained `gtest` includes.
- By setting `include_directories`, this directory was added as an include dir for every target that vt builds. This is what caused the conflict when we tried to build the in-house gtest.
To fix this, I removed the call to `include_directories`; the correct includes will be propagated correctly, as @cz4rs [pointed out](https://github.com/DARMA-tasking/vt/pull/2329#discussion_r1681420310)
> #2321: Build system is mixing the system googletest headers with our internal googletest

- scripts/JSON_data_files_validator.py
- scripts/check_lb_data_files.sh
Validate that comm links correctly reference tasks.
Fixes #2300 
Depends on #2305
> #2300: Create a JSON validator that runs on all JSON produced by CI

- ci/build_cpp.sh
- cmake-modules/Findlibunwind.cmake
- cmake/check_system_functions.cmake
- cmake/link_vt.cmake
- cmake/load_libunwind.cmake
- cmake/load_packages.cmake
- cmake_config.h.in
- src/vt/configs/error/stack_out.cc
- src/vt/configs/features/features_defines.h
- tests/unit/configs/test_stack_dumping.cc
Fixes #2320
The issue was that there were two versions of libunwind available, and we were trying to link with the wrong one.
I've added a `Findlibunwind.cmake` module so we can use `find_package(libunwind)` instead of `check_include_file`.
This gives us more control over which libunwind is found. Specifically, we can provide `HINTS` that point to the desired `libunwind` installation (usually, we want the one installed in `/usr`)
- I've added a `libunwind_ROOT_DIR` CMake variable that users can optionally provide during configuration. (This directory becomes the `HINT` passed to `find_package`)
- If `libunwind` isn't found in the suggested directory, it searches using CMake's default path instead.
> #2320:  simulate_replay fails to link related to dumpStack

- src/vt/vrt/collection/balance/baselb/baselb.h
- src/vt/vrt/collection/balance/greedylb/greedylb.cc
- src/vt/vrt/collection/balance/hierarchicallb/hierlb.cc
- src/vt/vrt/collection/balance/temperedlb/temperedlb.cc
> #2299: Do not deploy LB when average load is smaller than estimated load balancing cost

- ci/docker/ubuntu-gnu-cpp.dockerfile
> #2340: Fix missing NumPy package

- .github/workflows/build-docs.yml
- ci/build_cpp.sh
- ci/docker/ubuntu-gnu-docs.dockerfile
fixes #2364 
2742e9e7fd0efb2695a7ce64ca9ffa4956b748e6 is a drive-by change to update Ubuntu version.
98595cc2fdaace8fc5456fc8112673e267741f67 is the actual fix, removing faulty assertion and pinning the library version to the latest.
Issue reported in `m.css`:
https://github.com/mosra/m.css/issues/251
Successful documentation build on this branch:
https://github.com/DARMA-tasking/vt/actions/runs/11581967895/job/32243909262?pr=2367
> #2364: fix documentation build

- ci/build_cpp.sh
- ci/deps/doxygen.sh
- ci/docker/ubuntu-gnu-docs.dockerfile
fixes #2368 
Pin Doxygen version to `1.8.16` and remove the workaround from #2367.
---
Successful run from this branch: https://github.com/DARMA-tasking/vt/actions/runs/11780656704/job/32811716629.
Examples of the affected pages:
- https://darma-tasking.github.io/docs/html/structvt_1_1rdma_1_1_handle.html
- https://darma-tasking.github.io/docs/html/structvt_1_1rdma_1_1_handle_3_01_t_00_01_e_00_01_index_t_00_01typename_01std_1_1enable__if__t_3_d15dac1b5db6e2bc0fb0b8aca42b1456.html
> #2368: avoid regression in Doxygen 1.9.1

- src/vt/configs/features/features_featureswitch.h
- src/vt/runtime/runtime_banner.cc
Fixes #2385 
Note: In following with the existing logic for printing compile-time options, there is no print when verbose prints are disabled.
> #2385: Print in VT header when verbose prints are enabled at compile-time

- src/vt/runnable/runnable.cc
> #2390: getRecentTime() should not be used when tracing is enabled

- src/vt/context/runnable_context/trace.cc
- src/vt/context/runnable_context/trace.h
- src/vt/objgroup/manager.impl.h
- src/vt/registry/auto/auto_registry_common.h
- src/vt/runnable/make_runnable.h
- src/vt/scheduler/scheduler.cc
- src/vt/scheduler/scheduler.h
- src/vt/trace/trace.cc
- src/vt/trace/trace.h
- src/vt/vrt/collection/balance/lb_invoke/lb_manager.cc
- src/vt/vrt/collection/manager.impl.h
- tests/unit/trace/test_runnable_context_trace.cc
> #2389: trace: start tracing invoke calls 

- scripts/LBDatafile_schema.py
- src/vt/vrt/collection/balance/temperedlb/temperedlb.cc
- src/vt/vrt/collection/balance/temperedlb/temperedlb.h
> #2382: ccm-lb: add backoff to avoid performance issues w/locking

- .clang-format
- .github/workflows/run-clang-format.yml
fixes #2378 
- update our `.clang-format` file to better match project's style guidelines
- add a CI check to run `clang-format` on the PR changes and post a comment with the output (see https://github.com/DARMA-tasking/vt/pull/2379#issuecomment-2683363054 for an example)
The new `PR checks (clang-format)` workflow will NOT fail when the style is not applied, for now this is purely informative.
---
Misc notes:
- Official style guidelines: https://github.com/DARMA-tasking/vt/wiki/Code-Style-Guidelines
- It is possible to disable formatting for a section of code with:
```
// clang-format off
...
// clang-format on
```
> #2378: update `.clang-format` to match style guidelines

- examples/lb_data/lb_data_file_example.json
- src/vt/runtime/component/base.h
- src/vt/runtime/component/component.h
- src/vt/runtime/component/component_dep.h
- src/vt/runtime/component/component_pack.cc
- src/vt/runtime/component/component_pack.h
- src/vt/runtime/component/component_pack.impl.h
- src/vt/runtime/component/component_registry.h
- src/vt/runtime/runtime.cc
- tests/unit/runtime/test_component_construction.cc
> #2403: runtime: seperate out runtime dependencies from startup dependencies

- src/vt/pipe/callback/callback_base_tl.h
- src/vt/runtime/component/component_pack.impl.h
Fixes #2416
I didn't audit all of the codebase for this, but this appears to be all that clang 20 warns on
> #2416: remove a few unnecessary template keyword uses
