DARMA-tasking/vt

src/vt/runtime/runtime.cc
src/vt/trace/trace.cc
src/vt/trace/trace.h

* Corrected the default values for the directory and filename when tracing is enabled.

Fix printing of directory and file names for tracing.

---

cmake/link_vt.cmake
examples/broadcast_test.cc
src/vt/parameterization/parameterization.h
src/vt/registry/auto/auto_registry.h
src/vt/registry/auto/auto_registry_impl.h
src/vt/registry/auto/auto_registry_interface.h
src/vt/serialization/messaging/serialized_param_messenger.h
src/vt/utils/demangle/demangled_name.h
src/vt/vrt/collection/holders/holder.impl.h

Same as https://github.com/DARMA-tasking/vt/pull/496 without https://github.com/DARMA-tasking/vt/pull/496/commits/b7be7ec1486d43dc37d26463dc0019fda5c0c652

457 cleanup gcc warnings

---

src/vt/termination/interval/integral_set.h

470 work around icc bug

---

src/vt/vrt/collection/balance/baselb/baselb.cc
src/vt/vrt/collection/balance/hierarchicallb/hierlb.cc
src/vt/vrt/collection/balance/hierarchicallb/hierlb.h
src/vt/vrt/collection/balance/hierarchicallb/hierlb_msgs.h

Adds in new bug fix for EMPIRE:
`507-hierlb-race-condition`

1.0.0 beta.2 proposed update

---

src/vt/messaging/irecv_holder.h

Issue #524.  Addresses warnings resulting from #473.

524 remove signedness warnings

---

src/vt/configs/arguments/args.cc
src/vt/configs/arguments/args.h
src/vt/messaging/active.cc
src/vt/messaging/active.h
src/vt/messaging/irecv_holder.h
src/vt/runtime/runtime.cc
src/vt/trace/trace.cc

552 add tracing of mpi calls (for develop)

---

src/vt/messaging/collection_chain_set.h
src/vt/messaging/dependent_send_chain.h

New issue for #560 with correct branch name

#558 migrate object control flow

---

src/vt/group/collective/group_info_collective.cc

#568 group fix incorrect subtree size

---

src/vt/vrt/collection/manager.impl.h

Fix a race condition in collections manifested with priorities.
Fixes #572

#572 fix race condition in broadcast delivery

---

src/vt/vrt/collection/balance/elm_stats.impl.h

#589 Do not call LB on single node (fixes FPE in stats)

---

src/vt/group/group_manager.cc

#591 Fix bad captured stack pointer

---

CMakeLists.txt
cmake/define_build_types.cmake
cmake/link_vt.cmake
cmake_config.h.in
src/CMakeLists.txt
src/vt/configs/features/features_defines.h
src/vt/sequence/seq_context.h
src/vt/sequence/seq_ult_context.cc
src/vt/sequence/seq_ult_context.h
src/vt/sequence/sequencer.impl.h

#581 Disable fcontext lib by default

---

src/vt/vrt/collection/balance/gossiplb/gossiplb.cc
src/vt/vrt/collection/balance/gossiplb/gossiplb.h

Fix bugs in GossipLB causing bad load distributions.
Fixes #608

608 gossiplb bugs

---

src/vt/trace/trace.cc
src/vt/trace/trace.h

#617 Fix trace memory leaks when runtime-disabled, compile-time enabled

---

src/vt/trace/trace_containers.cc

#611 Move statics for trace to function to fix bug w/clang 3.9

---

src/vt/messaging/active.cc

https://github.com/DARMA-tasking/vt/pull/620 mirror to develop as previously mentioned; different branch of yer pretty tracker. Should close #619 right after.

619 tr begin may be used uninitialized (to develop)

---

src/vt/messaging/collection_chain_set.h

#615 Termination use DS-epoch by default for collection chain nextStep

---

src/vt/objgroup/manager.cc
src/vt/runnable/general.h

Fixes #610
This needs to be rebased when #613 gets merged.

#610 Fix objgroup local trace bug

---

src/vt/collective/collective_ops.cc
src/vt/configs/arguments/args.cc
src/vt/configs/arguments/args.h
src/vt/runtime/runtime.cc
src/vt/trace/trace.cc
src/vt/trace/trace.h
src/vt/trace/trace_common.h
src/vt/trace/trace_log.h
src/vt/trace/trace_registry.cc
src/vt/trace/trace_registry.h
src/vt/vrt/collection/manager.cc
src/vt/vrt/collection/manager.h

- Incorporate the changes from [#241 ](https://github.com/DARMA-tasking/vt/issues/241) to get a cleaner history.
- Merge "manually" the changes from [#600 ]
- Close the pull request [#551 ]

241 flush cleaner

---

src/vt/sequence/seq_list.cc

Refactor an explicit 'new' to clarify that it's a shared_ptr

---

src/vt/configs/arguments/args.cc
src/vt/configs/arguments/args.h
src/vt/runtime/runtime.cc
src/vt/scheduler/scheduler.cc
src/vt/scheduler/scheduler.h
tests/unit/scheduler/test_scheduler_progress.cc

630 progress function

---

src/vt/messaging/active.impl.h
src/vt/messaging/pending_send.cc
src/vt/messaging/pending_send.h
tests/unit/active/test_pending_send.cc

628 pending send bug

---

examples/transpose.cc

* With GCC7 on Linux, mpirun -np 4 ./tranpose.exe can result in a segmentation fault.
* The issue occurs when the initialization is not complete (i.e. the array `data_` is not resized) and the code goes through the second broadcast. It sets up the group and tries to access entries in `data_` without checking the size of `data_`.
* We added a reduction to check that the initialization is complete before setting up the group.
Fixes #634

#634 Fix memory bug in transpose example

---

src/vt/vrt/collection/balance/gossiplb/gossiplb.cc

#651: gossiplb: fix bug

---

src/vt/trace/trace.cc
src/vt/trace/trace_log.h

663 trace fix warnings on gcc-7

---

src/vt/vrt/collection/balance/baselb/baselb.h
src/vt/vrt/collection/balance/gossiplb/gossiplb.cc
src/vt/vrt/collection/balance/hierarchicallb/hierlb.cc

673 print stats after

---

src/vt/trace/trace.cc

676 trace fix user event cur event

---

src/vt/trace/trace.cc

Fixes #682
Another shot at fixing the user event bug. The increments were not happening in the correct sequence.

682 fix user event trace incrementing

---

src/vt/collective/barrier/barrier.cc
src/vt/configs/arguments/args.cc
src/vt/configs/arguments/args.h
src/vt/handler/handler.cc
src/vt/handler/handler.h
src/vt/messaging/active.cc
src/vt/messaging/active.h
src/vt/messaging/active.impl.h
src/vt/messaging/envelope/envelope_base.h
src/vt/messaging/envelope/envelope_get.h
src/vt/messaging/envelope/envelope_get.impl.h
src/vt/messaging/envelope/envelope_set.h
src/vt/messaging/envelope/envelope_set.impl.h
src/vt/messaging/envelope/envelope_setup.impl.h
src/vt/runnable/collection.h
src/vt/runnable/collection.impl.h
src/vt/runnable/general.impl.h
src/vt/runtime/runtime.cc
src/vt/serialization/messaging/serialized_messenger.h
src/vt/serialization/messaging/serialized_messenger.impl.h
src/vt/termination/dijkstra-scholten/comm.cc
src/vt/termination/termination.cc
src/vt/topos/location/location.impl.h
src/vt/trace/trace.cc
src/vt/trace/trace.h
src/vt/vrt/collection/manager.h
src/vt/vrt/collection/manager.impl.h
src/vt/vrt/collection/messages/user.h
src/vt/vrt/collection/messages/user.impl.h
tests/unit/scheduler/test_scheduler_priorities.cc

#631 trace system events

---

src/vt/vrt/collection/balance/gossiplb/gossiplb.cc
src/vt/vrt/collection/balance/gossiplb/gossiplb.h

691 GossipLB: re-compute PMF each assignment, loosen underloaded

---

src/vt/trace/trace_log.h

697 Trace: fix hiding member warning

---

src/vt/lb/instrumentation/entity.cc

699 Fix missing static declarations

---

examples/broadcast_test.cc
src/vt/collective/barrier/barrier.cc
src/vt/collective/collective_ops.cc
src/vt/runtime/runtime.cc
src/vt/scheduler/scheduler.cc
src/vt/scheduler/scheduler.h
src/vt/termination/term_scope.cc
src/vt/termination/termination.cc
src/vt/trace/trace.cc
src/vt/trace/trace.h
src/vt/vrt/collection/balance/gossiplb/gossiplb.cc
src/vt/vrt/collection/balance/lb_invoke/invoke.cc
src/vt/vrt/collection/manager.impl.h

703 mixed idle events pop beta.6

---

src/vt/configs/types/types_sentinels.h
src/vt/event/event.cc
src/vt/vrt/collection/balance/lb_invoke/invoke.cc

742 Event optimization

---

src/vt/utils/memory/memory_reporter.h
src/vt/utils/memory/memory_usage.h

752 memory destructors

---

src/vt/messaging/collection_chain_set.h

Fixes #754
Needed by Matt in EMPIRE

#754 Add traverse methods for indices in chain set

---

src/CMakeLists.txt
src/vt/topos/location/cache/cache.h
src/vt/topos/location/directory/directory.h
src/vt/topos/location/directory/directory.impl.h
src/vt/topos/location/location.h
src/vt/topos/location/location.impl.h
src/vt/topos/location/lookup/lookup.h
src/vt/topos/location/lookup/lookup.impl.h
src/vt/vrt/collection/manager.impl.h
tests/unit/location/test_location.cc

Fixes #744 
This fixes and very difficult to find bug in EMPIRE due to cache entires expiring that are not allowed to expire given the algorithm.

744 Fix location bug

---

tutorial/tutorial_2b.h

760 Tutorial: work around bug in collection buffering

---

src/vt/messaging/irecv_holder.h

767 irecv holder fix

---

src/vt/configs/arguments/args.cc
src/vt/configs/arguments/args.h
src/vt/event/event.cc
src/vt/event/event.h
src/vt/messaging/active.cc
src/vt/messaging/active.h
src/vt/messaging/irecv_holder.h
src/vt/runtime/runtime.cc

772 user trace components

---

src/vt/topos/location/location.h
src/vt/topos/location/location.impl.h
src/vt/topos/location/message/msg.h
tests/unit/location/test_hops.cc

765 location hops fix

---

src/vt/configs/arguments/args.cc
src/vt/configs/arguments/args.h
src/vt/configs/debug/debug_print.h
src/vt/runtime/runtime.cc

Fixes #778
Runtime implementation based on needs in EMPIRE.

778 always flush

---

src/vt/vrt/collection/balance/baselb/baselb.cc
src/vt/vrt/collection/balance/gossiplb/gossiplb.cc
src/vt/vrt/collection/balance/hierarchicallb/hierlb.cc

776 after lb stats fix

---

src/vt/vrt/collection/balance/elm_stats.h
src/vt/vrt/collection/migrate/manager_migrate_attorney.h
src/vt/vrt/collection/types/base.h
src/vt/vrt/collection/types/base.impl.h
src/vt/vrt/collection/types/indexable.h
src/vt/vrt/collection/types/indexable.impl.h
src/vt/vrt/collection/types/migratable.cc
src/vt/vrt/collection/types/migratable.fwd.h
src/vt/vrt/collection/types/migratable.h
src/vt/vrt/collection/types/migratable.impl.h

#781 Clear out pointless templates

---

src/vt/collective/reduce/operators/default_op.impl.h
src/vt/group/collective/group_info_collective.cc
src/vt/pipe/callback/proxy_send/callback_proxy_send.h
src/vt/pipe/pipe_manager_tl.h
src/vt/termination/termination.cc
src/vt/vrt/collection/balance/baselb/baselb.cc
src/vt/vrt/collection/balance/elm_stats.impl.h
src/vt/vrt/collection/balance/gossiplb/gossiplb.cc
src/vt/vrt/collection/proxy.h
src/vt/vrt/proxy/collection_proxy.h
src/vt/vrt/proxy/collection_proxy.impl.h

This rebases #784 for the release branch

#708 Add interface for recording and focusing a subphase in load balancing

---

src/vt/collective/reduce/operators/default_op.impl.h
src/vt/configs/arguments/args.cc
src/vt/configs/arguments/args.h
src/vt/configs/debug/debug_print.h
src/vt/event/event.cc
src/vt/event/event.h
src/vt/group/collective/group_info_collective.cc
src/vt/messaging/active.cc
src/vt/messaging/active.h
src/vt/messaging/irecv_holder.h
src/vt/pipe/callback/proxy_send/callback_proxy_send.h
src/vt/pipe/pipe_manager_tl.h
src/vt/runtime/runtime.cc
src/vt/termination/termination.cc
src/vt/topos/location/location.h
src/vt/topos/location/location.impl.h
src/vt/topos/location/message/msg.h
src/vt/vrt/collection/balance/baselb/baselb.cc
src/vt/vrt/collection/balance/elm_stats.cc
src/vt/vrt/collection/balance/elm_stats.h
src/vt/vrt/collection/balance/elm_stats.impl.h
src/vt/vrt/collection/balance/gossiplb/gossiplb.cc
src/vt/vrt/collection/balance/gossiplb/gossiplb.h
src/vt/vrt/collection/balance/hierarchicallb/hierlb.cc
src/vt/vrt/collection/proxy.h
src/vt/vrt/proxy/collection_proxy.h
src/vt/vrt/proxy/collection_proxy.impl.h

Merge to finalize beta.7 into 1.0.0.

Merge 1.0.0 beta.7 proposed update into 1.0.0

---

src/vt/worker/worker_stdthread.cc
src/vt/worker/worker_stdthread.h

797 Remove unused variable causing clang warning

---

src/CMakeLists.txt
src/vt/messaging/active.cc
src/vt/runtime/runtime.cc
src/vt/utils/mpi_limits/mpi_max_tag.cc
src/vt/utils/mpi_limits/mpi_max_tag.h

802 Wrap tag around when hits MPI max tag (attribute MPI_TAG_UB)

---

cmake/define_build_types.cmake
src/vt/configs/debug/debug_masterconfig.h

814 Include vt/ in cmake_config.h path to avoid ambiguity

---

src/vt/utils/demangle/demangle.cc
src/vt/utils/demangle/demangle.h
tests/CMakeLists.txt
tests/unit/utils/test_demangler_utils.cc

Fixes and off-by-one bug and adds tests.

789 - Fix function name in Trace having last character removed

---

ci/build_cpp.sh
ci/docker/ubuntu-18.04-gnu-cpp.dockerfile
cmake/define_build_types.cmake
cmake/link_vt.cmake
cmake/load_packages.cmake
cmake/load_zoltan_package.cmake
cmake_config.h.in
docker-compose.yml
scripts/get_zoltan.sh
src/CMakeLists.txt
src/vt/configs/features/features_defines.h
src/vt/configs/features/features_featureswitch.h
src/vt/runtime/runtime.cc
src/vt/vrt/collection/balance/lb_comm.h
src/vt/vrt/collection/balance/lb_invoke/invoke.cc
src/vt/vrt/collection/balance/lb_type.cc
src/vt/vrt/collection/balance/lb_type.h
src/vt/vrt/collection/balance/zoltanlb/zoltanlb.cc
src/vt/vrt/collection/balance/zoltanlb/zoltanlb.h

Fixes #584
Add Zoltan as an LB option. Generate vertex graph along with edges in the compressed edge format.

584 Implement LB for Zoltan

---

README.md

837 Rewrite README.md

---

src/vt/runtime/runtime.cc

844: Fix bug accessing theSched() when runtime is inactive

---

examples/hello_world/param.cc

851 Fix param.cc example compilation under CUDA

---

tests/unit/scheduler/test_scheduler_loop.cc

Just test ack to avoid entering an out-of-order wait.
Fixes #853

#853 Tests only: fix race condition in scheduler loop tests

---

docs/Doxyfile.in
docs/md/proc-stats.md

889 export \internal docs, add LB stats file description

---

src/vt/vrt/collection/balance/baselb/baselb.cc
src/vt/vrt/collection/balance/baselb/baselb.h
src/vt/vrt/collection/balance/elm_stats.impl.h
src/vt/vrt/collection/balance/gossiplb/gossiplb.cc
src/vt/vrt/collection/balance/greedylb/greedylb.cc
src/vt/vrt/collection/balance/hierarchicallb/hierlb.cc
src/vt/vrt/collection/balance/lb_invoke/lb_manager.cc
src/vt/vrt/collection/balance/lb_invoke/lb_manager.h
src/vt/vrt/collection/balance/randomlb/randomlb.cc
src/vt/vrt/collection/balance/rotatelb/rotatelb.cc
src/vt/vrt/collection/balance/statsmaplb/statsmaplb.cc
src/vt/vrt/collection/balance/zoltanlb/zoltanlb.cc
src/vt/vrt/collection/manager.cc
src/vt/vrt/collection/manager.impl.h

Fixes #827
This should also: Fixes #885

827 Refactor load balancing to allow running strategies abstractly from inputs and effects

---

.github/workflows/check-commit-format.yml
.github/workflows/check-trailing-whitespace.yml
.github/workflows/run-git-check.yml
src/vt/vrt/collection/manager.h
src/vt/vrt/context/context_vrtmessage.h

893 Add GitHub Actions for code quality checks

---

src/CMakeLists.txt

905 add proper cmake depends for MPI guards generation

---

src/vt/utils/adt/histogram_approx.h
tests/unit/utils/test_histogram_approx.cc

Fixes #920 
I've spun off the streaming histogram as a separate PR from #882 
This is an implementation of the paper:  "A Streaming Parallel Decision Tree Algorithm" by Ben-Haim and Tom-Tov: [Paper link](http://www.jmlr.org/papers/volume11/ben-haim10a/ben-haim10a.pdf)

920 Implement streaming histogram

---

.github/workflows/macosx-clang-mpich.yml

931 fix Mac CI target

---

docker-compose.yml
docs/md/lb-manager.md

943 Fix load model docs

---

src/vt/vrt/collection/balance/lb_invoke/lb_manager.cc
src/vt/vrt/collection/balance/model/comm_overhead.cc
src/vt/vrt/collection/balance/model/raw_data.cc
tests/unit/collection/test_lb.extended.cc

946 Fix LB bug in load model and add new LB tests

---

.github/workflows/macosx-clang-mpich.yml

951 Try to fix Mac CI failure

---

src/vt/vrt/collection/balance/model/linear_model.cc
src/vt/vrt/collection/balance/model/norm.h

One bug, one disused variable.
Fixes: #956

956 Load models: Correct unused variables

---

src/vt/runtime/component/component.h
src/vt/runtime/component/component_pack.cc
src/vt/runtime/component/component_pack.h
src/vt/runtime/component/component_pack.impl.h
src/vt/runtime/component/component_traits.h
src/vt/runtime/component/movable_fn.h
tests/unit/runtime/test_component_construction.cc

971 Fix component construction

---

tests/unit/timetrigger/test_time_trigger.extended.cc

976 Relax time trigger test to fix CI intermittent failures

---

tests/unit/timetrigger/test_time_trigger.extended.cc

981 Relax time trigger test again using new percent tolerance

---

docs/md/lb-manager.md
src/vt/configs/arguments/app_config.h
src/vt/configs/arguments/args.cc
src/vt/runtime/runtime_banner.cc
src/vt/vrt/collection/balance/lb_invoke/lb_manager.cc
src/vt/vrt/collection/balance/read_lb.cc
src/vt/vrt/collection/balance/read_lb.h
tests/unit/lb/test_lb_reader.cc

984 Print LB specification at startup (from file)

---

src/vt/timetrigger/time_trigger_manager.cc
src/vt/timetrigger/time_trigger_manager.h
src/vt/timetrigger/trigger.h
tests/unit/timetrigger/test_time_trigger.extended.cc

987 Unit test time-based triggers independent of clock

---

src/vt/scheduler/scheduler.cc

- Not neccessary and over-restriction for edge case.

#1003 schedule- remove idle-assert

---

src/vt/event/event.cc
src/vt/messaging/active.cc

Fixes #1018
- Some of leaks were caused by some refactoring a long time ago
- A couple other of the leaks are just missing cleanup

1018 Fix event leaks/growth

---

src/vt/vrt/collection/balance/model/load_model.h
src/vt/vrt/collection/balance/model/select_subphases.cc
tests/unit/collection/test_model_linear_model.nompi.cc
tests/unit/collection/test_model_multiple_phases.nompi.cc
tests/unit/collection/test_model_naive_persistence.nompi.cc

1034 load model lifecycle

---

src/vt/configs/arguments/args.h

1044 Write adaptor for develop AppConfig

---

src/vt/collective/reduce/reduce.h

#954: Document TD reasoning of reductions

---

src/vt/vrt/collection/balance/elm_stats.cc
src/vt/vrt/collection/balance/elm_stats.h

1033 Add getter for subphase on element stats

---

src/vt/configs/features/features_enableif.h

1047 check enabled compatibility with develop

---

.github/workflows/dockerimage-gcc-7-ubuntu-mpich.yml
scripts/workflows.ini
src/vt/collective/reduce/reduce.impl.h

1042 Cleanup memory growing unbounded in reduce manager

---

src/vt/vrt/collection/balance/lb_invoke/lb_manager.cc

#1056: Run LB starting after phase 1 by default

---

src/vt/vrt/collection/balance/model/raw_data.cc
src/vt/vrt/collection/balance/node_stats.cc
tests/unit/collection/test_model_raw_data.nompi.cc

#1063 Properly record subphase timings

---

src/vt/vrt/collection/balance/model/load_model.h
tests/unit/collection/test_model_linear_model.nompi.cc
tests/unit/collection/test_model_multiple_phases.nompi.cc
tests/unit/collection/test_model_per_collection.extended.cc
tests/unit/collection/test_model_persistence_median_last_n.nompi.cc

#1060 Don't allow sloppy mis-construction of PhaseOffset

---

.github/workflows/check-pr-comment-fixes-issue.yml

1066 CI: run PR description check always

---

src/vt/vrt/collection/balance/baselb/baselb.cc

#1071: Count all migrations where they originate, so that total migration count reduction is accurate

---

src/vt/topos/location/location.h
src/vt/topos/location/location.impl.h
src/vt/vrt/collection/manager.impl.h
tests/unit/location/test_location.cc

Function calls changed.
Fixes #746

#746 adjust location manager migration nomenclature

---

ci/build_cpp.sh

1083 When building docs, clone into lib for docs generation

---

src/vt/collective/reduce/reduce.impl.h
src/vt/group/collective/group_info_collective.cc
src/vt/messaging/envelope/envelope_set.h
src/vt/messaging/envelope/envelope_set.impl.h
src/vt/topos/location/location.h
src/vt/topos/location/location.impl.h
src/vt/vrt/collection/manager.impl.h

Another exception for a handler-forwarding cases.
fixes #1074

#1074 Additional msg unlocking

---

src/vt/vrt/collection/balance/randomlb/randomlb.cc

1097 RandomLB vary across phases

---

src/vt/runtime/runtime.cc
src/vt/vrt/collection/balance/lb_invoke/lb_manager.cc
src/vt/vrt/collection/balance/node_stats.cc
src/vt/vrt/collection/balance/node_stats.h
src/vt/vrt/collection/manager.cc
tests/unit/collection/test_lb.extended.cc
tests/unit/test_parallel_harness.h

#1014: dump node stats before trimming

---

examples/callback/callback.cc
examples/collection/lb_iter.cc
examples/hello_world/hello_world_collection_collective.cc
src/vt/vrt/collection/manager.h
src/vt/vrt/collection/manager.impl.h
tests/unit/collection/test_checkpoint.extended.cc
tests/unit/collection/test_lb.extended.cc
tests/unit/collection/test_model_per_collection.extended.cc
tests/unit/location/test_hops.extended.cc
tests/unit/rdma/test_rdma_collection_handle.extended.cc

1023 Add default function for user-constructing collection elements

---

.github/workflows/check-commits-are-signed.yml

#1061 add action to check if PR's commits are signed

---

docs/md/lb-manager.md

1120 Fix spelling of ZoltanLB in manual

---

cmake-modules/GoogleTest.cmake
cmake-modules/GoogleTestAddTests.cmake
docker-compose.yml
snippets/minimal-large-send-test.cc
snippets/minimal-rdma-test.cc
src/vt/pmpi/generate_mpi_wrappers.pl
src/vt/rdmahandle/holder.impl.h
src/vt/rdmahandle/lock_mpi.h
src/vt/rdmahandle/request_holder.cc
tests/unit/location/test_location_common.h
tests/unit/rdma/test_rdma_collection_handle.extended.cc
tests/unit/test_parallel_harness.h

Fixes #1134 
Pulled out from work stemming from #1111, which was interleaved

1134 Fix tests not running

---

src/vt/utils/bits/bits_packer.impl.h
tests/unit/utils/test_bit_packing.nompi.cc

1114 Fix bit twiddling bug

---

src/vt/collective/startup.cc
src/vt/collective/startup.h
tests/unit/runtime/test_initialization.nompi.cc

1163: fix initialization with no arguments

---

cmake/define_build_types.cmake
docs/md/building.md

1162: Make vt_lb_enabled default ON in cmake

---

ci/build_cpp.sh

#1156: check if ccache exists before calling it

---

examples/callback/callback_context.cc
src/vt/objgroup/manager.cc
src/vt/objgroup/manager.h
src/vt/objgroup/proxy/proxy_objgroup.h
src/vt/objgroup/proxy/proxy_objgroup.impl.h
src/vt/objgroup/proxy/proxy_objgroup_elm.h
src/vt/objgroup/proxy/proxy_objgroup_elm.impl.h
tests/unit/collectives/test_collectives_reduce.extended.cc
tests/unit/test_parallel_harness.h
tutorial/tutorial_1d.h
tutorial/tutorial_1h.h

#973: implement default proxy

---

ci/azure/azure-clang-3.9-ubuntu-mpich.yml
ci/azure/azure-clang-5.0-ubuntu-mpich.yml
ci/azure/azure-clang-8-alpine-mpich.yml
ci/azure/azure-gcc-10-ubuntu-openmpi.yml
ci/azure/azure-gcc-5-ubuntu-mpich.yml
ci/azure/azure-gcc-6-ubuntu-mpich.yml
ci/azure/azure-gcc-7-ubuntu-mpich.yml
ci/azure/azure-gcc-8-ubuntu-mpich.yml
ci/azure/azure-gcc-9-ubuntu-mpich.yml
ci/azure/azure-intel-18-ubuntu-mpich-extended.yml
ci/azure/azure-intel-18-ubuntu-mpich.yml
ci/azure/azure-intel-19-ubuntu-mpich.yml
ci/azure/azure-nvidia-10-ubuntu-mpich-extended.yml
ci/azure/azure-nvidia-10-ubuntu-mpich.yml
ci/azure/azure-nvidia-11-ubuntu-mpich-extended.yml
ci/azure/azure-nvidia-11-ubuntu-mpich.yml
scripts/azure-workflow-template.yml

#1219: Run commentary task only for PRs

---

ci/build_cpp.sh

#1227: don't run tests if compilation failed

---

examples/collection/jacobi1d_vt.cc
examples/collection/jacobi2d_vt.cc
examples/collection/reduce_integral.cc

1126: Add collective calls for VT examples

---

tutorial/tutorial_1e.h
tutorial/tutorial_1f.h
tutorial/tutorial_1h.h
tutorial/tutorial_main.h

1261: Use collective epochs for tutorial examples

---

.github/workflows/comment-on-pr.yml

#1239 - add comment-on-pr action

---

ci/azure/azure-clang-3.9-ubuntu-mpich.yml
ci/azure/azure-clang-5.0-ubuntu-mpich.yml
ci/azure/azure-clang-8-alpine-mpich.yml
ci/azure/azure-gcc-10-ubuntu-openmpi.yml
ci/azure/azure-gcc-5-ubuntu-mpich.yml
ci/azure/azure-gcc-6-ubuntu-mpich.yml
ci/azure/azure-gcc-7-ubuntu-mpich.yml
ci/azure/azure-gcc-8-ubuntu-mpich.yml
ci/azure/azure-gcc-9-ubuntu-mpich.yml
ci/azure/azure-intel-18-ubuntu-mpich-extended.yml
ci/azure/azure-intel-18-ubuntu-mpich.yml
ci/azure/azure-intel-19-ubuntu-mpich.yml
ci/azure/azure-nvidia-10-ubuntu-mpich-extended.yml
ci/azure/azure-nvidia-10-ubuntu-mpich.yml
ci/azure/azure-nvidia-11-ubuntu-mpich-extended.yml
ci/azure/azure-nvidia-11-ubuntu-mpich.yml
scripts/azure-workflow-template.yml

Fixes #1239 
Workflow defined here -> https://github.com/DARMA-tasking/vt/blob/develop/.github/workflows/comment-on-pr.yml
(merge commit - 9870c7683c4ad73f77efb0aefa786f19c07e6bde)
The Action itself is here -> https://github.com/DARMA-tasking/comment-on-pr

1239 update existing PR comments

---

examples/rdma/rdma_simple_put.cc
src/vt/group/global/group_default.cc
tests/unit/active/test_active_bcast_put.cc
tests/unit/active/test_active_broadcast.cc
tests/unit/location/test_location.cc

1286: Fix bcast issue introduced with #883

---

src/vt/phase/phase_manager.cc
src/vt/phase/phase_manager.h
src/vt/vrt/collection/manager.impl.h
tests/unit/phase/test_phase_insertions.cc

1166 Set proper phase when element is inserted

---

src/vt/topos/location/location.h
src/vt/topos/location/location.impl.h
src/vt/vrt/collection/manager.h
src/vt/vrt/collection/manager.impl.h
src/vt/vrt/collection/messages/system_create.h
tests/unit/phase/test_phase_insertions.cc

1300 Make collection element insertion idempotent

---

src/vt/messaging/active.cc

1307: fix warnings on release branch

---

ci/azure/azure-clang-3.9-ubuntu-mpich.yml
ci/azure/azure-clang-5.0-ubuntu-mpich.yml
ci/azure/azure-clang-8-alpine-mpich.yml
ci/azure/azure-gcc-10-ubuntu-openmpi.yml
ci/azure/azure-gcc-5-ubuntu-mpich.yml
ci/azure/azure-gcc-6-ubuntu-mpich.yml
ci/azure/azure-gcc-7-ubuntu-mpich.yml
ci/azure/azure-gcc-8-ubuntu-mpich.yml
ci/azure/azure-gcc-9-ubuntu-mpich.yml
ci/azure/azure-intel-18-ubuntu-mpich-extended.yml
ci/azure/azure-intel-18-ubuntu-mpich.yml
ci/azure/azure-intel-19-ubuntu-mpich.yml
ci/azure/azure-nvidia-10-ubuntu-mpich-extended.yml
ci/azure/azure-nvidia-10-ubuntu-mpich.yml
ci/azure/azure-nvidia-11-ubuntu-mpich-extended.yml
ci/azure/azure-nvidia-11-ubuntu-mpich.yml
scripts/azure-workflow-template.yml
scripts/report_logs_in_comment.sh
tests/unit/collection/test_lb.extended.cc

#1291: export tests logs to PR comment

---

scripts/report_logs_in_comment.sh
tests/unit/collection/test_lb.extended.cc

#1323 fix compilation tests reporting

---

.github/workflows/comment-on-pr.yml
ci/azure/azure-clang-3.9-ubuntu-mpich.yml
ci/azure/azure-clang-5.0-ubuntu-mpich.yml
ci/azure/azure-clang-8-alpine-mpich.yml
ci/azure/azure-gcc-10-ubuntu-openmpi.yml
ci/azure/azure-gcc-5-ubuntu-mpich.yml
ci/azure/azure-gcc-6-ubuntu-mpich.yml
ci/azure/azure-gcc-7-ubuntu-mpich.yml
ci/azure/azure-gcc-8-ubuntu-mpich.yml
ci/azure/azure-gcc-9-ubuntu-mpich.yml
ci/azure/azure-intel-18-ubuntu-mpich-extended.yml
ci/azure/azure-intel-18-ubuntu-mpich.yml
ci/azure/azure-intel-19-ubuntu-mpich.yml
ci/azure/azure-nvidia-10-ubuntu-mpich-extended.yml
ci/azure/azure-nvidia-10-ubuntu-mpich.yml
ci/azure/azure-nvidia-11-ubuntu-mpich-extended.yml
ci/azure/azure-nvidia-11-ubuntu-mpich.yml
scripts/azure-workflow-template.yml
scripts/report_logs_in_comment.sh

#1320: put a direct link to Azure builds in PR comment

---

.github/workflows/macosx-clang-mpich.yml
ci/Brewfile
ci/deps/mpich.sh
src/vt/context/context.cc

1336: macosx-clang build fails when using latest macos image

---

lib/context/CMakeLists.txt
lib/context/check_valgrind.cmake
lib/context/context_config.h.in
lib/context/src/context/context_stack.cc
lib/context/valgrind_stack_register.cmake.cc

1345: context: register stack with valgrind

---

src/vt/trace/trace_common.h

1385: Fix nvcc warning about sign mismatch

---

CMakeLists.txt
cmake-modules/SetCXXCompilerFlags.cmake
cmake/check_compiler.cmake
cmake/load_bundled_libraries.cmake
src/CMakeLists.txt
src/vt/pipe/pipe_manager_base.impl.h

#1402: Don't doubly-request C++14 standard support in ways that can break things

---

ci/build_cpp.sh
ci/docker/ubuntu-18.04-gnu-docs.dockerfile

1401: documentation fails to build

---

.clang-format

#1399 clean up clang-format config file

---

src/vt/context/runnable_context/lb_stats.h
src/vt/context/runnable_context/lb_stats.impl.h
src/vt/runnable/make_runnable.h
src/vt/runnable/runnable.h
src/vt/vrt/collection/manager.impl.h

1407 Fix invoke context for collection element invoke

---

CMakeLists.txt
lib/fmt/CMakeLists.txt

1413: cmake: Fix nvcc warnings

---

ci/azure/azure-gcc-10-ubuntu-openmpi-spack.yml

#1430 disable spack pipeline in PRs

---

src/vt/vrt/collection/balance/lb_invoke/invoke.cc

Fixes #1366 on the release branch.

1366 LB strategy name can skip validation

---

src/vt/vrt/collection/balance/gossiplb/gossiplb.cc
src/vt/vrt/collection/balance/gossiplb/gossiplb.h

Fixes #1387 on the release branch.

1387 gossiplb fanout type

---

ci/azure/azure-clang-10-ubuntu-mpich.yml
ci/azure/azure-clang-3.9-ubuntu-mpich.yml
ci/azure/azure-clang-5.0-ubuntu-mpich.yml
ci/azure/azure-clang-8-alpine-mpich.yml
ci/azure/azure-clang-9-ubuntu-mpich.yml
ci/azure/azure-gcc-10-ubuntu-openmpi.yml
ci/azure/azure-gcc-5-ubuntu-mpich.yml
ci/azure/azure-gcc-6-ubuntu-mpich.yml
ci/azure/azure-gcc-7-ubuntu-mpich.yml
ci/azure/azure-gcc-8-ubuntu-mpich.yml
ci/azure/azure-gcc-9-ubuntu-mpich.yml
ci/azure/azure-intel-18-ubuntu-mpich-extended.yml
ci/azure/azure-intel-18-ubuntu-mpich.yml
ci/azure/azure-intel-19-ubuntu-mpich.yml
ci/azure/azure-nvidia-10-ubuntu-mpich-extended.yml
ci/azure/azure-nvidia-10-ubuntu-mpich.yml
ci/azure/azure-nvidia-11-ubuntu-mpich-extended.yml
ci/azure/azure-nvidia-11-ubuntu-mpich.yml
ci/test_cpp.sh
docker-compose.yml
scripts/azure-workflow-template.yml

#1398 remove codecov token

---

src/vt/vrt/collection/balance/baselb/baselb.cc
src/vt/vrt/collection/balance/baselb/baselb.h
src/vt/vrt/collection/balance/gossiplb/gossiplb.cc
src/vt/vrt/collection/balance/gossiplb/gossiplb.h
tests/unit/lb/test_gossiplb.nompi.cc

Fixes #1369 on the release branch. #1370 already put this on develop.

1369 implement additional gossiplb ordering

---

tests/CMakeLists.txt
tests/unit/sequencer/test_sequencer_extensive.extended.cc
tests/unit/termination/test_term_dep_send_chain.cc

1427: Fix issues with Azure tests

---

ci/docker/ubuntu-18.04-nvidia-cpp.dockerfile

#1254 change nvcc_wrapper link to release 3.4.00

---

src/vt/messaging/dependent_send_chain.h
src/vt/phase/phase_manager.cc
src/vt/rdmahandle/sub_handle.impl.h
src/vt/runtime/runtime_diagnostics.cc
src/vt/scheduler/scheduler.impl.h
src/vt/vrt/collection/balance/baselb/baselb.cc
src/vt/vrt/collection/balance/gossiplb/gossiplb.cc
src/vt/vrt/collection/balance/lb_invoke/lb_manager.cc
src/vt/vrt/collection/balance/zoltanlb/zoltanlb.cc
src/vt/vrt/collection/manager.impl.h

1437: Label all uses of runInEpochCollective in source code

---

src/vt/messaging/active.impl.h
src/vt/serialization/messaging/serialized_messenger.impl.h
tests/unit/active/test_active_send.cc
tests/unit/runtime/test_mpi_access_guards.cc

Fixes #1447 
TODO:
- @cz4rs: Please write a test that exposes this bug so we can confirm it fixes it.
- We have tested bvh/NimbleSM and this fix seems to work.

1447 Fix bug in epoch transfer for serialized messages

---

src/vt/configs/arguments/app_config.h
src/vt/configs/arguments/args.cc
src/vt/runtime/runtime.cc
src/vt/runtime/runtime.h
src/vt/runtime/runtime_banner.cc

Fixes #1282: added the handler and related command line option.

#1282 Add SIGBUS to set of handled signals

---

src/vt/messaging/active.cc
src/vt/messaging/active.h
src/vt/messaging/active.impl.h
src/vt/messaging/async_op_cuda.h

1477 Import AsyncOp(CUDA) updates from EMPIRE

---

src/vt/vrt/collection/manager.h
src/vt/vrt/collection/manager.impl.h

1497 Implement function for collections to get local indices

---

src/vt/utils/memory/memory_usage.cc

#1505: Fix warning about unused private member

---

cmake/link_vt.cmake

Fixes application builds.
Fixes #1509

1509: build: make json headers public

---

src/vt/messaging/async_op_cuda.h

#1564: Print CUDA error details when one occurs

---

src/vt/configs/arguments/app_config.h
src/vt/configs/arguments/args.cc
src/vt/runtime/runtime.cc
src/vt/vrt/collection/balance/greedylb/greedylb.cc
src/vt/vrt/collection/balance/greedylb/greedylb.h
src/vt/vrt/collection/balance/hierarchicallb/hierlb.cc
src/vt/vrt/collection/balance/hierarchicallb/hierlb.h
src/vt/vrt/collection/balance/lb_invoke/lb_manager.cc
src/vt/vrt/collection/balance/lb_invoke/lb_manager.h
src/vt/vrt/collection/balance/randomlb/randomlb.cc
src/vt/vrt/collection/balance/randomlb/randomlb.h
src/vt/vrt/collection/balance/rotatelb/rotatelb.cc
src/vt/vrt/collection/balance/rotatelb/rotatelb.h
src/vt/vrt/collection/balance/statsmaplb/statsmaplb.h
src/vt/vrt/collection/balance/temperedlb/temperedlb.cc
src/vt/vrt/collection/balance/temperedlb/temperedlb.h
src/vt/vrt/collection/balance/zoltanlb/zoltanlb.cc
src/vt/vrt/collection/balance/zoltanlb/zoltanlb.h

1359: LB: write docs for args to LBs

---

ci/test_spack_package.sh

Fixes #1571 
What was done:
1. Use fixed version of spack (v0.16.3)
2. Convert env variables into boolean variants, that are expected after implementing https://github.com/DARMA-tasking/spack-package/issues/12

#1571 fix spack package pipeline

---

src/vt/epoch/epoch_window.cc

1590 Epoch: fix unconditional prints

---

CMakeLists.txt
cmake/trace_only_functions.cmake
src/CMakeLists.txt

#1581 remove redundant setting of 'position independent code' property

---

src/vt/termination/epoch_guard.cc
src/vt/termination/epoch_guard.h
tests/unit/termination/test_epoch_guard.cc

#1476: epoch guard

---

ci/build_vt_sample.sh

#1611 disable vt-sample-project build on Alpine pipelines

---

src/vt/vrt/collection/balance/stats_data.cc
tests/unit/collection/test_lb.extended.cc

#1589 Read in communication data from json files

---

src/vt/vrt/collection/insert/modify_token.h

#1620 add move assignment to ModifierToken

---

src/vt/vrt/collection/balance/stats_msg.h

#1628: Prevent division by zero

---

.github/workflows/check-pr-comment-fixes-issue.yml

#1633 check branch naming only when PR's targetting develop branch

---

src/vt/context/runnable_context/collection.h
src/vt/context/runnable_context/collection.impl.h
src/vt/topos/location/manager.h
src/vt/topos/location/manager.impl.h
src/vt/vrt/collection/collection_builder.impl.h
src/vt/vrt/collection/holders/col_holder.h
src/vt/vrt/collection/holders/col_holder.impl.h
src/vt/vrt/collection/holders/elm_holder.h
src/vt/vrt/collection/holders/elm_holder.impl.h
src/vt/vrt/collection/holders/entire_holder.h
src/vt/vrt/collection/holders/entire_holder.impl.h
src/vt/vrt/collection/holders/holder.h
src/vt/vrt/collection/holders/holder.impl.h
src/vt/vrt/collection/manager.h
src/vt/vrt/collection/manager.impl.h
src/vt/vrt/collection/messages/user.h
src/vt/vrt/collection/param/construct_params.h
src/vt/vrt/collection/types/base.h
src/vt/vrt/collection/types/base.impl.h
src/vt/vrt/collection/types/indexable.h
src/vt/vrt/collection/types/indexable.impl.h

1639 Reduce templates

---

src/vt/vrt/collection/balance/col_stats.impl.h
src/vt/vrt/collection/balance/greedylb/greedylb.cc
src/vt/vrt/collection/balance/hierarchicallb/hierlb.cc
src/vt/vrt/collection/balance/lb_invoke/lb_manager.cc
src/vt/vrt/collection/balance/lb_invoke/lb_manager.h
src/vt/vrt/collection/balance/node_stats.h

#1627: Narrow inclusion of stats_msg.h

---

src/vt/collective/reduce/reduce_scope.h
src/vt/collective/reduce/scoping/strong_types.h
src/vt/elm/elm_comm.h
src/vt/rdma/channel/rdma_channel_lookup.h
src/vt/topos/index/dense/dense_array.impl.h
src/vt/utils/adt/union.h
src/vt/utils/hash/hash_tuple.h
src/vt/utils/memory/memory_units.h
src/vt/utils/strong/strong_type.h
src/vt/vrt/collection/balance/greedylb/greedylb.h
src/vt/vrt/collection/balance/lb_common.h
src/vt/vrt/collection/balance/lb_type.h
src/vt/vrt/collection/balance/temperedlb/tempered_enums.h
src/vt/vrt/proxy/base_elm_proxy.h
src/vt/vrt/proxy/collection_elm_proxy.h

#1452 remove 'using vt::...' declarations polluting std namespace

---

ci/build_cpp.sh

1652: docs: do not customize m.css library

---

lib/context/CMakeLists.txt

1650 -- fcontext: check if architecture matches aarch64

---

src/vt/messaging/active.cc

1445: active: schedule messages on self-send

---

src/vt/termination/termination.h
src/vt/vrt/collection/collection_builder.impl.h
tests/unit/collection/test_mapping.cc

1673 runInEpochRooted should by default use a DS epoch

---

src/vt/collective/reduce/reduce.impl.h
src/vt/messaging/active.cc
src/vt/objgroup/manager.static.h
src/vt/pipe/callback/handler_send/callback_send.impl.h
src/vt/pipe/callback/handler_send/callback_send_tl.impl.h
src/vt/runnable/make_runnable.h
src/vt/serialization/messaging/serialized_messenger.impl.h
src/vt/topos/location/location.impl.h

Fixes #1685 
Follow-up to refactor is in issue #1687

1685 Fix tracing issue

---

examples/collection/lb_iter.cc

1689 Add subphases to lb_iter example

---

src/CMakeLists.txt

Fixes #1696 
---
I tested it also in https://github.com/DARMA-tasking/vt/pull/1694 where I was getting some gcc7 failures, and it helped there.

#1696 switch code coverage to -Og

---

src/vt/collective/reduce/reduce.impl.h
src/vt/context/runnable_context/trace.cc
src/vt/context/runnable_context/trace.h
src/vt/context/runnable_context/trace.impl.h
src/vt/handler/handler.cc
src/vt/handler/handler.h
src/vt/messaging/active.cc
src/vt/messaging/active.h
src/vt/objgroup/manager.static.h
src/vt/parameterization/parameterization.h
src/vt/pipe/callback/handler_send/callback_send.impl.h
src/vt/pipe/callback/handler_send/callback_send_tl.impl.h
src/vt/rdma/state/rdma_state.cc
src/vt/registry/auto/auto_registry.cc
src/vt/registry/auto/auto_registry_common.h
src/vt/registry/auto/auto_registry_impl.h
src/vt/registry/auto/auto_registry_interface.h
src/vt/registry/auto/auto_registry_type_enum.h
src/vt/registry/auto/collection/auto_registry_collection.impl.h
src/vt/registry/auto/functor/auto_registry_functor_impl.h
src/vt/registry/auto/map/auto_registry_map_impl.h
src/vt/registry/auto/rdma/auto_registry_rdma.impl.h
src/vt/runnable/make_runnable.h
src/vt/serialization/messaging/serialized_messenger.impl.h
src/vt/topos/location/location.impl.h
src/vt/vrt/collection/manager.impl.h
src/vt/vrt/context/context_vrtinfo.cc
tests/unit/handler/test_handler.cc

#1687 encode RegistryTypeEnum in HandlerType bits

---

src/vt/context/runnable_context/base.h
src/vt/context/runnable_context/lb_stats.h
src/vt/messaging/active.cc
src/vt/messaging/active.h

1669: Move the duplicated setup code for LB stats into separate function

---

src/vt/collective/reduce/operators/default_op.impl.h
src/vt/context/runnable_context/base.h
tests/unit/collectives/test_collectives_reduce.cc

1704 Fix envelope locking error in envelope and add test

---

src/vt/objgroup/manager.cc
src/vt/objgroup/manager.h
src/vt/objgroup/manager.impl.h
src/vt/objgroup/proxy/proxy_bits.cc
src/vt/objgroup/proxy/proxy_bits.h
src/vt/objgroup/proxy/proxy_objgroup.h
src/vt/objgroup/proxy/proxy_objgroup.impl.h
src/vt/vrt/collection/balance/lb_invoke/lb_manager.cc

#879: objgroup: remove type bits from objgroup proxy

---

src/vt/vrt/collection/balance/lb_common.h
src/vt/vrt/collection/balance/lb_invoke/lb_manager.cc
src/vt/vrt/collection/balance/lb_invoke/lb_manager.h

1724 Use callbacks for reassignment post lb and statistics

---

src/vt/objgroup/manager.h
tests/unit/collection/test_collection_group.extended.cc
tests/unit/objgroup/test_objgroup.cc

#1551 test references breaking when sending locally

---

tests/unit/collection/test_checkpoint.extended.cc

#1709: add checkpoint test

---

src/vt/messaging/pending_send.fwd.h
src/vt/objgroup/manager.fwd.h
src/vt/objgroup/manager.h
src/vt/objgroup/manager.impl.h
src/vt/objgroup/proxy/proxy_objgroup.h
src/vt/objgroup/proxy/proxy_objgroup.impl.h
src/vt/objgroup/proxy/proxy_objgroup_elm.h
src/vt/objgroup/proxy/proxy_objgroup_elm.impl.h
tests/unit/active/test_pending_send.cc
tests/unit/objgroup/test_objgroup.cc
tests/unit/objgroup/test_objgroup_common.h

#1662: make objgroup send and broadcast return pendingsend

---

.gitlab-ci.yml
ci/build_cpp.sh

#1768: CI: add test, try to fix clone error

---

.gitlab-ci.yml

#1770: CI: change tag for CI dispatch

---

.gitlab-ci.yml
ci/build_cpp.sh
cmake/configure_options.cmake
cmake_config.h.in
tests/unit/rdma/test_rdma_collection_handle.extended.cc
tests/unit/rdma/test_rdma_handle.cc
tests/unit/rdma/test_rdma_handle.extended.cc
tests/unit/rdma/test_rdma_static_sub_handle.extended.cc

#1772: CI: add option to disable RDMA tests

---

.gitlab-ci.yml

#1777: CI: move proxy exports to before build

---

.gitlab-ci.yml

#1779: CI: actually add Intel 19, fix misleading name

---

cmake/check_system_functions.cmake
cmake_config.h.in
src/vt/configs/error/stack_out.cc
tests/unit/configs/test_stack_dumping.cc

1691 build fails in the absence of libunwind

---

src/vt/configs/arguments/args.cc

#1717 LB: add .br extension for compressed data files

---

.gitlab-ci.yml

#1792: CI: submit as a job

---

.gitlab-ci.yml

#1796: CI: try to fix Vortex

---

ci/build_cpp.sh

1814 Add parallelism option to build_cpp script

---

ci/build_cpp.sh

1816 fix parallelism option in build_cpp script

---

tests/unit/collection/test_lb_lite.extended.cc
tests/unit/collection/test_mapping.cc

1820 Fix declaration hides member warnings

---

ci/azure/azure-intel-oneapi-icpc-ubuntu-mpich.yml
ci/docker/ubuntu-intel-oneapi-cpp.dockerfile
docker-compose.yml
scripts/workflows-azure.ini

1808: Add build for the latest icpc version

---

ci/azure/azure-clang-alpine-mpich.yml
ci/docker/alpine-cpp.dockerfile
scripts/workflows-azure.ini

1822: Upgrade CI docker image to Alpine 3.16

---

src/vt/collective/scatter/scatter.cc
src/vt/collective/scatter/scatter.impl.h
src/vt/messaging/active.cc
src/vt/messaging/active.h
src/vt/messaging/active.impl.h
src/vt/messaging/message/message.h
src/vt/messaging/message/shared_message.impl.h
src/vt/messaging/message/smart_ptr.h
src/vt/pool/pool.cc
src/vt/pool/pool.h
src/vt/rdma/rdma.cc
tests/unit/collection/test_send.cc
tests/unit/collection/test_send.h

#1795: store message size in allocated memory block

---

scripts/JSON_data_files_validator.py
scripts/check_lb_data_files.sh

- added JSON_data_files_validator.py as one file to scripts
- removed cloning LBAF repository from check_lb_data_files.sh and changed path to the JSON_data_files_validator.py script
@lifflander Jonathan, please take a look at that and test. I have moved the `JSON_data_files_validator.py` to one file. I have noticed you have already added `Schema` and `brotli`, so I haven't done anything regarding that. I removed cloning `LBAF` repo from the shell script you wrote as well as changed path to `JSON_data_files_validator.py` file, because they are in the same directory.
closes #1863

#1726: Moved Schema Validator to VT

---

src/vt/messaging/active.cc
src/vt/objgroup/manager.cc
src/vt/phase/phase_hook_enum.h
src/vt/phase/phase_hook_id.h
src/vt/phase/phase_manager.cc
src/vt/phase/phase_manager.h
src/vt/trace/trace.cc
src/vt/utils/memory/memory_usage.cc
src/vt/vrt/collection/balance/lb_invoke/lb_manager.cc
src/vt/vrt/collection/broadcast/broadcastable.h
src/vt/vrt/collection/broadcast/broadcastable.impl.h
src/vt/vrt/collection/manager.cc
src/vt/vrt/collection/manager.h
src/vt/vrt/collection/manager.impl.h

1764 make phase transition less expensive

---

src/vt/messaging/active.cc

1910 Break out early

---

src/vt/runtime/runtime.cc

1915 Cache TD pointer

---

src/vt/messaging/message/message_priority.impl.h
src/vt/scheduler/base_unit.h
src/vt/scheduler/prioritized_work_unit.h
src/vt/scheduler/queue.h

Fixes #1944 
Enabling fixes toward runnable creation/running/scheduling optimization.

1944 failure to compile with priorities disabled

---

cmake/configure_options.cmake
tests/unit/scheduler/test_scheduler_priorities.extended.cc

Fixes #1945 
Unneeded overhead by default.

1945 disable priorities by default

---

src/vt/pool/static_sized/memory_pool_equal.cc
src/vt/pool/static_sized/memory_pool_equal.h

1913 Add option of headerless pool

---

src/vt/runtime/runtime.h

1959 fix build failures due to sequencer removal

---

src/vt/scheduler/base_unit.h
src/vt/scheduler/queue.h
src/vt/utils/container/circular_buffer.h
tests/unit/utils/test_circular_buffer.nompi.cc

1950 use circular buffer to increase efficiency of scheduling

---

src/vt/messaging/envelope/envelope_base.h
src/vt/messaging/envelope/envelope_extended.h
src/vt/messaging/envelope/payload_envelope.h
src/vt/termination/interval/integral_set.h

Old PR: https://github.com/DARMA-tasking/vt/pull/1975
Fixes #1974

#1974: fix various c++17 deprecations

---

scripts/report_logs_in_comment.sh

#1940: add commit date in CI results comment

---

examples/collection/CMakeLists.txt
examples/collection/polymorphic_collection.cc

2005 write polymorphic collection example

---

examples/collection/polymorphic_collection.cc

#2015: Adjust `num_elems` in polymorphic_collection example if `num_nodes` is greater than `default_num_elems`

---

src/vt/context/runnable_context/set_context.cc
src/vt/context/runnable_context/set_context.h
src/vt/scheduler/thread_action.cc
tests/unit/active/test_async_op_threads.cc
tests/unit/scheduler/test_thread_actions.cc

2028 setcontext doesnt suspend correct task with threads

---

docs/Doxyfile.in

#2013: Fix warning during generation of doxygen documentation

---

ci/docker/ubuntu-nvidia-cpp.dockerfile

#2078: CI: use the release version of nvcc_wrapper

---

src/vt/messaging/async_op_hip.h
tests/unit/active/test_async_op_hip.cc

1671: Messaging: Add HIP version of AsyncOp

---

src/vt/registry/auto/auto_registry_common.h
src/vt/vrt/collection/broadcast/broadcastable.impl.h
src/vt/vrt/collection/manager.h
src/vt/vrt/collection/manager.impl.h
src/vt/vrt/collection/types/base.h
tests/unit/collection/test_promote.cc

2102 collection broadcast loses message data

---

src/vt/configs/arguments/app_config.h
src/vt/configs/arguments/args.cc
src/vt/runtime/runtime.cc
src/vt/runtime/runtime_banner.cc

2086 loosen when lbdatarestartreader is created

---

CMakeLists.txt
ci/azure/azure-clang-10-ubuntu-mpich.yml
ci/azure/azure-clang-11-ubuntu-mpich.yml
ci/azure/azure-clang-12-ubuntu-mpich.yml
ci/azure/azure-clang-13-ubuntu-mpich.yml
ci/azure/azure-clang-14-ubuntu-mpich.yml
ci/azure/azure-clang-9-ubuntu-mpich.yml
ci/azure/azure-clang-alpine-mpich.yml
ci/azure/azure-gcc-10-ubuntu-openmpi.yml
ci/azure/azure-gcc-11-ubuntu-mpich.yml
ci/azure/azure-gcc-12-ubuntu-mpich.yml
ci/azure/azure-gcc-7-ubuntu-mpich.yml
ci/azure/azure-gcc-8-ubuntu-mpich.yml
ci/azure/azure-gcc-9-ubuntu-mpich.yml
ci/azure/azure-intel-oneapi-icpc-ubuntu-mpich.yml
ci/azure/azure-intel-oneapi-icpx-ubuntu-mpich.yml
ci/azure/azure-nvidia-11-2-ubuntu-mpich.yml
ci/azure/azure-nvidia-11-ubuntu-mpich.yml
ci/docker/ubuntu-18.04-gnu-docs.dockerfile
ci/docker/ubuntu-20.04-gnu-openmpi-cpp.dockerfile
ci/docker/ubuntu-clang-cpp.dockerfile
ci/docker/ubuntu-gnu-cpp.dockerfile
ci/docker/ubuntu-nvidia-cpp.dockerfile
scripts/check_containers.sh
scripts/workflow-azure-template.yml

#2115: Update CMake min required version to 3.23

---

ci/azure/azure-nvidia-12-ubuntu-mpich.yml
scripts/workflows-azure.ini

#2142: ci: upgrade CUDA workflow from 11.0 to 12.1.0

---

.github/workflows/build-docs.yml
docker-compose.yml

#2158: Add missing env variable and fix dockerfile name

---

src/vt/vrt/collection/balance/lb_data_holder.cc
tests/unit/collection/test_lb_data_holder.cc

#2162: Fix vt aborting when lb file dont have metadata

---

src/vt/vrt/collection/balance/baselb/baselb.cc
src/vt/vrt/collection/balance/baselb/baselb.h
src/vt/vrt/collection/balance/lb_common.h
src/vt/vrt/collection/balance/lb_data_holder.h
src/vt/vrt/collection/balance/lb_invoke/lb_manager.cc
src/vt/vrt/collection/balance/node_lb_data.cc
src/vt/vrt/collection/balance/node_lb_data.h
src/vt/vrt/collection/types/storage/storable.h
src/vt/vrt/collection/types/storage/storable.impl.h
src/vt/vrt/collection/types/storage/store_elm.h
tests/unit/collection/test_lb.extended.cc

#2176: lb: add user-defined data for LB

---

src/vt/vrt/collection/manager.impl.h
tests/unit/collection/test_collection_manager.cc

#2238: Fix crash from missing proxy in CollectionManager

---

src/vt/elm/elm_lb_data.cc
src/vt/elm/elm_lb_data.h

2261 Add support code for simulating load from within an application

---

src/vt/vrt/collection/balance/lb_invoke/lb_manager.cc

#2266: lbmanager: print lb time only on rank 0

---

src/vt/vrt/collection/balance/workload_replay.cc

#2265: replay: remove timing of lb

---

src/vt/serialization/messaging/serialized_messenger.impl.h
tests/unit/serialization/test_serialize_messenger.cc

#2273: serialization: fix memory leak in local send

---

examples/collection/CMakeLists.txt
examples/collection/jacobi3d_vt.cc

fixes #1701.   I am adding a new example program.

#1701: Adding a 3D example program based on the 2D version.

---

src/vt/vrt/collection/balance/lb_data_holder.cc
src/vt/vrt/collection/balance/lb_data_holder.h
tests/unit/collection/test_lb.extended.cc

2279: Bug in communication JSON output

---

ci/azure/azure-clang-16-ubuntu-mpich.yml
scripts/workflows-azure.ini

#2330: Add clang-16 pipeline

---

docs/md/trace.md
src/vt/event/event.cc
src/vt/messaging/active.cc
src/vt/messaging/request_holder.h
src/vt/trace/trace.cc
src/vt/trace/trace_lite.cc
src/vt/trace/trace_lite.h
src/vt/trace/trace_log.h
src/vt/trace/trace_user.cc
src/vt/trace/trace_user.h
tests/unit/trace/test_trace_user.cc

#2187: nested trace user events output in wrong order

---

scripts/LBDatafile_schema.py

#2350: Improve logic in LBDatafile_schema

---

scripts/LBDatafile_schema.py

#2352: Add latest changes to 1.5.0 release

---

src/vt/messaging/message/smart_ptr.h

#2354 Use new checkpoint::is_footprinter_v

---

.github/workflows/check-include-guards-and-license.yml
examples/collection/jacobi1d_vt.cc
examples/collection/jacobi2d_vt.cc
examples/collection/jacobi3d_vt.cc
examples/hello_world/hello_world.cc

#2362: Clean up examples

---

.github/workflows/macosx-clang-mpich.yml

#2370: upgrade macOS runner image

---

scripts/LBDatafile_schema.py

Fixes #2375
Linked to:
- https://github.com/DARMA-tasking/LB-analysis-framework/pull/563
- https://github.com/DARMA-tasking/vt-tv/pull/129

#2375: scripts: add lb_iterations to JSON data file schema validator

---

src/vt/runtime/runtime_banner.cc

#2391: Print when LB statistics are off

---

examples/lb_data/lb_data_file_example.json
scripts/LBDatafile_schema.py

#2409: Add new and optional key for rank-local alpha to VT JSON schema

---

src/vt/runtime/runtime.cc
src/vt/vrt/collection/manager.impl.h

#2411: Unregister locations of destroyed collection elements

---

src/vt/rdma/rdma_common.h
src/vt/vrt/collection/balance/greedylb/greedylb.h

#2418: fmt: fix dangling pointer when formatting

---

cmake/load_bundled_libraries.cmake

#2424 Update fmt version
